-- # VORP Items — fx-camping

-- Run this SQL against your database to register all items.

INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`)
VALUES
    ('tent_open',           'Open Tent',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('tent_hunter',         'Hunter Tent',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('tent_mountain',       'Mountain Tent',          100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('tent_rain',           'Rain Tent',              100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('tent_tanner',         'Tanner Tent',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('tent_lemoyne',        'Lemoyne Tent',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('tent_hide_small',     'Small Hide Tent',        100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('tent_bison',          'Bison Tent',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('tent_swamp',          'Swamp Tent',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('tent_mulch',          'Mulch Tent',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('shelter_leanto',      'Lean-To Shelter',        100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('shelter_debris',      'Debris Shelter',         100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('caravan_wagon',       'Caravan Wagon',          100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('table_wood',          'Wooden Table',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('chair_wood',          'Wooden Chair',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('bench_wood',          'Wooden Bench',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('cot',                 'Cot',                    100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('table_bespoke',       'Bespoke Table',          100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('stool_folding',       'Folding Stool',          100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('chair_folding',       'Folding Chair',          100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('chair_rustic',        'Rustic Chair',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('bed_native_small',    'Small Native Bed',       100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('bed_native_large',    'Large Native Bed',       100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('bedroll',             'Bedroll',                100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('backrest',            'Backrest',               100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('log_bench_large',     'Large Log Bench',        100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('log_bench_small',     'Small Log Bench',        100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('log_bench_medium',    'Medium Log Bench',       100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('bonfire',             'Bonfire',                100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('campfire_1',          'Campfire 1',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('campfire_2',          'Campfire 2',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('campfire_3',          'Campfire 3',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('campfire_4',          'Campfire 4',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('campfire_5',          'Campfire 5',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('firepit',             'Fire Pit',               100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('kettle_fire',         'Kettle Fire',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('bread_oven',          'Bread Oven',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('forge',               'Forge',                  100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('anvil',               'Anvil',                  100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('anvil_stump',         'Anvil Stump',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('sawhorse',            'Sawhorse',               100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('workbench',           'Workbench',              100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('grindstone',          'Grindstone',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('coal_bin',            'Coal Bin',               100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('lantern_oil',         'Oil Lantern',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('lamp_street',         'Street Lamp',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('light_post',          'Light Post',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('chest_small',         'Small Chest',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('chest_large',         'Large Chest',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('trunk',               'Trunk',                  100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('barrel',              'Barrel',                 100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('crate',               'Crate',                  100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('coffin',              'Coffin',                 100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('washbasin',           'Wash Basin',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('dirt_tub',            'Dirt Tub',               100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('rope_basket',         'Rope Basket',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('water_bucket',        'Water Bucket',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('grain_sack_a',        'Grain Sack A',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('grain_sack_b',        'Grain Sack B',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('gourd',               'Gourd',                  100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('basket_a',            'Basket A',               100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('basket_b',            'Basket B',               100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('pottery_a',           'Pottery A',              100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('pottery_b',           'Pottery B',              100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('pottery_c',           'Pottery C',              100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('bowl',                'Bowl',                   100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('cloth_pile',          'Cloth Pile',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('hide_roll',           'Hide Roll',              100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('totem_a',             'Totem A',                100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('totem_b',             'Totem B',                100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('totem_staff',         'Totem Staff',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('totem_c',             'Totem C',                100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('totem_d',             'Totem D',                100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('skull_stones',        'Skull Stones',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('skull_post',          'Skull Post',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('skull_tip_a',         'Skull Tip A',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('skull_tip_b',         'Skull Tip B',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('skull_totem_small',   'Small Skull Totem',      100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('stone_tomahawk',      'Stone Tomahawk',         100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('dreamcatcher',        'Dreamcatcher',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('feather_tip',         'Feather Tip',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('rattle_hanging',      'Hanging Rattle',         100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('dreamcatcher_bead',   'Bead Dreamcatcher',      100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('feather_decor',       'Feather Decor',          100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('skull_totem_large',   'Large Skull Totem',      100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('skull_spear_trio',    'Skull Spear Trio',       100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('bone_catcher',        'Bone Catcher',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('totem_hanging',       'Hanging Totem',          100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('bearskin',            'Bear Skin',              100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('cattle_skull',        'Cattle Skull',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('xmas_tree',           'Christmas Tree',         100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('xmas_candy',          'Christmas Candy',        100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('xmas_ginger',         'Gingerbread',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('xmas_gift',           'Christmas Gift',         100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('xmas_wreath',         'Christmas Wreath',       100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('hitchpost_wood',      'Wooden Hitchpost',       100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('target_practice',     'Practice Target',        100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('water_pump',          'Water Pump',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('strawman',            'Strawman',               100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('fence_a',             'Fence A',                100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('fence_b',             'Fence B',                100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('fence_wall_a',        'Fence Wall A',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('fence_wall_b',        'Fence Wall B',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('barricade',           'Barricade',              100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('bounty_board',        'Bounty Board',           100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('gatling_gun',         'Gatling Gun',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('jump_hay',            'Hay Jump',               100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('jump_fence',          'Fence Jump',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('jump_sack',           'Sack Jump',              100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('jump_barrel',         'Barrel Jump',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('jump_block',          'Block Jump',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('jump_dock',           'Dock Jump',              100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('jump_hurdle',         'Hurdle Jump',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('baby_stroller',       'Baby Stroller',          100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('gold_cradle',         'Gold Cradle',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('drying_rack',         'Drying Rack',            100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('hide_frame',          'Hide Frame',             100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('hitchpost_metal',     'Metal Hitchpost',        100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('counter_a',           'Counter A',              100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('counter_b',           'Counter B',              100, 1, 'item_standard', 1, '{}', 'Nice item'),
    ('vendor_cart',         'Vendor Cart',            100, 1, 'item_standard', 1, '{}', 'Nice item')

ON DUPLICATE KEY UPDATE
    `label`      = VALUES(`label`),
    `limit`      = VALUES(`limit`),
    `can_remove` = VALUES(`can_remove`),
    `type`       = VALUES(`type`),
    `usable`     = VALUES(`usable`),
    `metadata`   = VALUES(`metadata`),
    `desc`       = VALUES(`desc`);


