Language = {}

Language.en = {
    -- Search and Filtering
    ["SearchItemsPlaceholder"] = "Search items... (Ctrl+F)",
    ["Filters"] = "Filters",
    ["NoItemsFound"] = "No items found",
    ["TryAdjustingSearchOrFilters"] = "Try adjusting your search or filters",
    ["LoadingItems"] = "Loading items...",
    ["LoadingSettings"] = "Loading Settings",

    -- Favorites
    ["NoFavorites"] = "No favorites",
    ["AddToFavorites"] = "Add to favorites",
    ["RemoveFromFavorites"] = "Remove from favorites",
    ["FavoritesFull"] = "Favorites Full",
    ["FavoritesFullHint"] = "All favorite slots are full. Remove one first.",
    ["AddedToFavorites"] = "Added to Favorites",
    ["AddedToFavoritesDesc"] = "{name} added to slot {slot}",
    ["PressOrClickToSelect"] = "Press {label} or click to select",
    ["FavoriteEmptyHint"] = "Press",
    ["WhileHoveringAnItem"] = "while hovering an item",

    -- Grid and Items
    ["GridTooltipHint"] = "Left-click: Select to spawn • Right-click: Options",
    ["QuickSpawn"] = "Quick Spawn",
    ["ChooseVariant"] = "Choose Variant...",
    ["ShowDetails"] = "Show Details",
    ["BaseModel"] = "Base Model",
    ["ChooseVariantTitle"] = "Choose Variant",
    ["SelectVariantToSpawn"] = "Select a variant to spawn",
    ["VariantsAvailable"] = "{count} variant(s) available",

    -- Item Actions
    ["Selected"] = "Selected",
    ["SelectedDesc"] = "{name} selected - Click in world to spawn",
    ["Spawned"] = "Spawned",
    ["SpawnedDesc"] = "{name} spawned successfully",
    ["Deselected"] = "Deselected",
    ["ItemDeselected"] = "Item deselected",
    ["Error"] = "Error",
    ["FailedToSpawn"] = "Failed to spawn item",
    ["FailedToAddToFavorites"] = "Failed to add to favorites",
    ["FailedToUpdateFavorites"] = "Failed to update favorites",
    ["FailedToLoadCategories"] = "Failed to load categories",
    ["FailedToLoadItems"] = "Failed to load items",
    ["FailedToSaveSettings"] = "Failed to save settings",

    --Selection Options
    ["SelectionMode"] = "Selection Mode",
    ["ExcludeHorsesVehicles"] = "Exclude Vehicles",
    ["ExcludePeds"] = "Exclude Peds",
    ["IncludeObjects"] = "Include Objects",
    ["IncludePlayers"] = "Include Players",

    -- Spawn Options
    ["SpawnMode"] = "Spawn Mode",
    ["SpawnOnHorse"] = "Spawn on Horse",
    ["SpawnAsAmbient"] = "Spawn as Ambient",

    -- Walk Options
    ["WalkMode"] = "Walk Mode",
    ["Running"] = "Running",
    ["UsePathfindingAsDefault"] = "Use pathfinding as default",

    -- Settings
    ["Settings"] = "Settings",
    ["Appearance"] = "Appearance",
    ["Theme"] = "Theme",
    ["Dark"] = "Dark",
    ["HighContrast"] = "High Contrast",
    ["Auto"] = "Auto",
    ["GridSize"] = "HUD Size",
    ["Small"] = "Small",
    ["Medium"] = "Medium",
    ["Large"] = "Large",

    ["Behavior"] = "Behavior",
    ["ContextMenuItems"] = "Context Menu items",
    ["AutoSave"] = "Auto Save",
    ["AutoSaveHint"] = "Automatically save favorites and settings",
    ["ShowTooltips"] = "Show Tooltips",
    ["ShowTooltipsHint"] = "Display helpful tooltips on hover",
    ["SoundEffects"] = "Sound Effects",
    ["SoundEffectsHint"] = "Play sounds for actions",
    ["SoundVolume"] = "Sound Volume",
    ["ShowPedDetails"] = "Show Ped Details",
    ["ShowPedDetailsHint"] = "Display a compact info panel when one ped is selected",
    ["PedDetailsSize"] = "Ped Details Size",

    ["CameraModeToggle"] = "Camera Mode Toggle",
    ["CameraModeToggleHint"] = "Press MMB once to start camera rotation, press again to stop (instead of holding)",

    ["ShadowPeds"] = "Shadow Peds",
    ["ShadowPedsHint"] = "Show ghost preview ped while spawning",

    -- UI Actions
    ["Reset"] = "Reset",
    ["Cancel"] = "Cancel",
    ["Save"] = "Save",
    ["Send"] = "Send",
    ["Clear"] = "Clear",
    ["AdminMessage"] = "Admin Message",
    ["AdminMenu"] = "Admin",
    ["MessageToPlayer"] = "Message to player",
    ["TypeMessage"] = "Type a message...",
    ["Revive"] = "Revive",
    ["Freeze"] = "Freeze",
    ["TeleportToPlayer"] = "Teleport to Player",
    ["BringPlayer"] = "Bring Player",
    ["SpectatePlayer"] = "Spectate Player",
    ["KickPlayer"] = "Kick Player",
    ["KickReason"] = "Enter kick reason:",
    ["AdvancedActions"] = "Advanced Actions",
    ["SetHealth"] = "Set Health",
    ["SetArmor"] = "Set Armor",
    ["Set"] = "Set",
    ["GiveMoney"] = "Give Money",
    ["Give"] = "Give",
    ["GiveItem"] = "Give Item",
    ["ItemName"] = "Item name...",
    ["SetJob"] = "Set Job",
    ["JobName"] = "Job name...",
    ["GotIt"] = "Got it!",
    ["LeaveGamemaster"] = "Leave Gamemaster mode?",
    ["LeaveGamemasterHint"] = "You can re-enable it with the command again.",
    ["Confirm"] = "Confirm",

    -- Languages
    ["Language"] = "Language",
    ["English"] = "English",
    ["German"] = "German",
    ["French"] = "French",

    -- Help and UI
    ["HelpAndGuide"] = "Help & Guide",
    ["Minimize"] = "Minimize",
    ["Maximize"] = "Maximize",
    ["Close"] = "Close",
    ["Back"] = "Back",
    ["Next"] = "Next",
    ["Previous"] = "Previous",

    -- Network and Status
    ["NetworkedEntitiesInUse"] = "Networked entities in use. Above 90 risks performance; hard limit ~110.",
    ["LoadingNetworkUsage"] = "Loading network usage…",

    -- Categories and Filters
    ["Faction"] = "Faction",
    ["Weapon"] = "Weapon",
    ["BehaviorFilter"] = "Behavior",
    ["Gender"] = "Gender",
    ["Male"] = "Male",
    ["Female"] = "Female",
    ["Animals"] = "Animals",
    ["Lawman"] = "Lawman",
    ["Criminal"] = "Criminal",
    ["Neutral"] = "Neutral",
    ["Armed"] = "Armed",
    ["Unarmed"] = "Unarmed",
    ["Melee"] = "Melee",
    ["Friendly"] = "Friendly",
    ["Hostile"] = "Hostile",
    ["Horses"] = "Horses",
    ["Wild"] = "Wild",
    ["Domestic"] = "Domestic",
    ["Aquatic"] = "Aquatic",
    ["Birds"] = "Birds",
    ["Dangerous"] = "Dangerous",

    -- Radial Menu
    ["BindAction"] = "Bind an action",
    ["RemoveBinding"] = "Remove binding",

    -- Help Content
    ["GettingStarted"] = "Getting Started",
    ["SpawningItems"] = "Spawning Items",
    ["KeyboardShortcuts"] = "Keyboard Shortcuts",
    ["AdvancedFeatures"] = "Advanced Features",
    ["AboutGmHotbar"] = "About DD GM",
    ["Favorites"] = "Favorites",
    ["ClickSelectThenSpawn"] = "Left-click an item to select; then click in world to spawn",
    ["RightClickOptionsVariants"] = "Right-click an item for options and variants",
    ["SearchBarHint"] = "Use the search bar and filters to find items",
    ["DragToFavorites"] = "Drag items from the grid to the 1–9 slots below",
    ["PressDigitsSelectFavorite"] = "Press 1–9 to select a favorite",
    ["PressDigitsAssignFavorite"] = "Press 1–9 while hovering an item to assign it to a slot",
    ["CategoriesAndFilters"] = "Categories and Filters",
    ["SwitchCategories"] = "Switch between categories",
    ["UseFiltersToNarrow"] = "Use filters to narrow results",
    ["ResetClearsFiltersSearch"] = "Reset button clears all filters and search",
    ["CameraControls"] = "Camera Controls",
    ["Move"] = "Move",
    ["UpDown"] = "Up / Down",
    ["Sprint"] = "Sprint",
    ["Zoom"] = "Zoom",
    ["ZoomWheel"] = "Mouse Wheel",
    ["RotateCamera"] = "Rotate camera",
    ["Yaw"] = "Yaw",
    ["Pitch"] = "Pitch",
    ["Or"] = "or",
    ["SelectionActions"] = "Selection & Actions",
    ["SelectEntity"] = "Select entity under cursor",
    ["BoxSelect"] = "Box-select (drag)",
    ["OpenContextMenu"] = "Open context menu",
    ["MoveOrder"] = "Move order with selection",
    ["ReturnSelectMode"] = "Clear selection/ Leave GM Mode",
    ["CancelSpawnMode"] = "Cancel spawn mode",
    ["CopySelection"] = "Copy selection",
    ["PasteAtCursor"] = "Paste at cursor",
    ["CutSelection"] = "Cut selection",
    ["DeleteSelection"] = "Delete selection",
    ["VariantsHint"] = "Many items have multiple variants (small dot). Right-click to choose.",
    ["VariantsWeapons"] = "Different weapon loadouts for NPCs",
    ["VariantsColors"] = "Color variations for objects",
    ["VariantsPresets"] = "Modified presets with different parameters",
    ["SmartSearchHint"] = "Search is debounced and looks through names and tags:",
    ["SmartSearchExampleLawman"] = "finds law enforcement NPCs",
    ["SmartSearchExampleMale"] = "finds male NPCs",
    ["ActivityLogHint"] = "The log drawer tracks actions, with filtering and export. Useful for debugging or reviewing your session.",
    ["MarqueeSelection"] = "Marquee Selection",
    ["MarqueeSelectionHint"] = "Drag the left mouse in empty world space to box-select multiple entities.",
    ["PedInfoPanel"] = "Ped Info Panel",
    ["PedInfoPanelHint"] = "When exactly one ped is selected, a compact panel shows model, HP, weapon, relationship, and ownership.",
    ["Integrated"] = "Integrated",
    ["Active"] = "Active",
    ["LocalStorageAndServer"] = "Local Storage + Server",
    ["AboutIntegrationNote"] = "This UI is integrated with the Lua core via NUI. Spawns, selection, and orders work in-game. Favorites persist per character when available; local storage is used as a fallback.",
    ["Navigation"] = "Navigation",
    ["FocusSearch"] = "Focus search",
    ["PreviousPage"] = "Previous page",
    ["NextPage"] = "Next page",
    ["CloseOverlays"] = "Close overlays",
    ["SpawnFavorite"] = "Spawn favorite",
    ["ItemVariants"] = "Item Variants",
    ["SmartSearch"] = "Smart Search",
    ["ActivityLog"] = "Activity Log",
    ["RedmGamemasterTool"] = "DD Gamemaster Tool",
    ["IntegrationStatus"] = "Integration Status",
    ["TechnicalDetails"] = "Technical Details",
    ["ApiStatus"] = "API Status",
    ["NuiEvents"] = "NUI Events",
    ["DataPersistence"] = "Data Persistence",
    ["LocalStorage"] = "Local Storage",
    ["Framework"] = "Framework",
    ["Styling"] = "Styling",
    ["UiComponents"] = "UI Components",
    ["RedmGamemasterToolDesc"] = "This hotbar interface provides quick access to spawning Peds, objects, vehicles and managing preset scenarios in your Roleplay server. Built with a focus on efficiency and ease of use for game masters and administrators.",
    ["DevelopedBy"] = "Developed by",
    ["License"] = "License",
    ["Version"] = "Version",
    ["TabSelection"] = "Highlight all Peds",
    ["OpenTutorial"] = "Open tutorial",
    ["SelectFavorite"] = "Select favorite",
    ["DLCStatus"] = "DLC Status",
    ["DLCStatusDesc"] = "Currently no DLC is available.",

    -- Ped Detail Panel
    ["SelectionDetails"] = "Selection details ({count})",
    ["Entity"] = "Entity",
    ["EntityID"] = "ID {id}",
    ["Health"] = "Health",
    ["Follow"] = "Follow",
    ["Hold"] = "Hold",
    ["AttackOnSight"] = "Attack on sight",
    ["FollowSingleOnly"] = "Follow (single only)",
    ["HoldPosition"] = "Hold Position",
    ["AttackOnSightCapital"] = "Attack on Sight",
    ["GroupSettings"] = "Group Settings",
    ["PedSettings"] = "Ped Settings",
    ["AttackOnSightLabel"] = "Attack on Sight",
    ["None"] = "None",
    ["PlayersOnly"] = "Players Only",
    ["Everyone"] = "Everyone",
    ["CannotFlee"] = "Cannot flee",
    ["AttackRange"] = "Attack Range",
    ["Meters"] = "m",
    ["ShootingAccuracy"] = "Shooting Accuracy",
    ["Percent"] = "%",
    ["Groups"] = "Groups",
    ["GroupsWithCount"] = "Groups ({count} entities)",
    ["AllInGroup"] = "All in: {name}",
    ["NoGroupsYet"] = "No groups yet",
    ["NewGroupName"] = "New group name...",
    ["Remove"] = "Remove",

    -- Groups Panel
    ["GroupsCount"] = "{count} group(s)",
    ["NewGroup"] = "+ New Group",
    ["Members"] = "Members",
    ["NoGroupsCreated"] = "No groups created",
    ["CreateFirstGroup"] = "Create your first group to get started",
    ["MembersCount"] = "{count} member(s)",
    ["Creator"] = "Creator: {owner}",
    ["SelectAll"] = "Select All",
    ["SelectGroupToViewMembers"] = "Select a group to view members",
    ["NoMembersInGroup"] = "No members in this group",
    ["AddEntitiesToGetStarted"] = "Add entities to get started",
    ["GroupName"] = "Group name...",

    -- Context Menu Strings
    ["GoToDirect"] = "Go to directly",
    ["GoToPathfinding"] = "Go to with pathfinding",
    ["GoToAndStand"] = "Go to and stand",
    ["GoToMenu"] = "Go to...",
    ["AttackTarget"] = "Attack target",
    ["AttackInArea"] = "Attack in area",
    ["AttackMenu"] = "Attack...",
    ["ScenariosMenu"] = "Scenarios...",
    ["StandStill"] = "Stand still",
    ["BehaveAsAmbient"] = "Behave as Ambient",
    ["FollowPed"] = "Follow",
    ["StopFollowing"] = "Stop following",
    ["GiveWeaponMenu"] = "Give Weapon...",
    ["RemoveWeapon"] = "Remove Weapon",
    ["Dismount"] = "Dismount",
    ["Revive"] = "Revive",
    ["HealToFull"] = "Heal to full",
    ["Kill"] = "Kill",
    ["EnableGodmode"] = "Enable Godmode",
    ["DisableGodmode"] = "Disable Godmode",
    ["Freeze"] = "Freeze",
    ["Unfreeze"] = "Unfreeze",
    ["CancelAllTasks"] = "Cancel All Tasks",
    ["ClearTasksImmediately"] = "Clear Tasks Immediately",
    ["PedActionsMenu"] = "Ped Actions...",
    ["AnimationsMenu"] = "Animations...",
    ["RideHorse"] = "Ride horse",
    ["UnmountAllPassengers"] = "Unmount all passengers",
    ["DisableVehicle"] = "Disable vehicle",
    ["EnterVehicle"] = "Enter vehicle",
    ["EnterVehicleAll"] = "Enter vehicle (All)",
    ["UseScenario"] = "Use scenario",
    ["UseNearestScenarioWalk"] = "Use nearest scenario",
    ["UseNearestScenarioWarp"] = "Use nearest scenario (warp)",

    -- UI and Navigation
    ["OpenSettings"] = "Open Settings",
    ["OpenLog"] = "Open Log",
    ["OpenHelp"] = "Open Help",
    ["RemoveFromFavorites"] = "Remove from favorites",
    ["EmptySlot"] = "Empty Slot",
    ["Previous"] = "Previous",
    ["Next"] = "Next",
    ["PageOf"] = "Page {current} of {total}",
    ["ItemsTotal"] = "({count} items total)",
    ["Details"] = "Details",
    ["Clear"] = "Clear",
    ["EntriesCount"] = "{filtered} of {total} entries",
    ["NoLogsYet"] = "No logs yet",
    ["ActivityWillAppearHere"] = "Activity will appear here",
    ["NoLogsMatchFilter"] = "No logs match your filter",
    ["TryAdjustingSearchOrFilter"] = "Try adjusting your search or type filter",
    ["SelectedPed"] = "Selected Ped",
    ["Model"] = "Model",
    ["Hash"] = "Hash",
    ["HP"] = "HP",
    ["Weapon"] = "Weapon",
    ["Relationship"] = "Relationship",
    ["CanAttack"] = "Can Attack",
    ["Yes"] = "Yes",
    ["No"] = "No",
    ["Prop"] = "Prop",
    ["Holstered"] = "Holstered",
    ["Unarmed"] = "Unarmed",

    -- Selection/Clipboard
    ["SelectedUnits"] = "Selected: {count}",
    ["Copied"] = "Copied",
    ["CopiedSelectionDesc"] = "Copied {count} selected ped(s)",
    ["Pasted"] = "Pasted",
    ["PastedSelectionDesc"] = "Pasted {count} ped(s)",
    ["Cut"] = "Cut",
    ["CutSelectionDesc"] = "Cut {peds} ped(s){vehicles,select,0, ,1, and {vehicles} vehicle,other, and {vehicles} vehicles}",

    -- Network Pool Warning
    ["NotifyHighNetworkPoolTitle"] = "Network Pool Warning",
    ["NotifyHighNetworkPoolText"] = "High networked ped count: %s/110. Consider reducing spawned entities.",

    -- Impersonate
    ["Impersonate"] = "Impersonate",
    ["StopImpersonating"] = "Revert Impersonation",

    -- Object Placement Mode
    ["object_placement.title"] = "Object Placement",
    ["object_placement.free_move"] = "• LMB: Drag axis to move",
    ["object_placement.snap_ground"] = "• G: Snap to ground",
    ["object_placement.toggle_rotate"] = "• TAB: Toggle rotate",
    ["object_placement.drag_rotate"] = "• LMB: Drag ring to rotate",
    ["object_placement.toggle_translate"] = "• TAB: Toggle translate",
    ["object_placement.confirm_cancel"] = "• Enter: Confirm • RMB: Cancel",

    -- Object Modification Mode
    ["object_modification.title"] = "Modify Object",
    ["object_modification.start_modifying"] = "• Enter: Start modifying",
    ["object_modification.start_modifying_warning"] = "• Note: Non networked objects are not synced!",

    -- Elements DLC
    ["elements.Elements"] = "Elements",
    ["ElementsDLC"] = "Elements DLC",
    ["elements.CreateFire"] = "Create Fire",
    ["elements.DeleteFires"] = "Delete Fires",
    ["elements.LightningStrike"] = "Lightning Strike",
    ["elements.Explosions"] = "Explosions",
    ["elements.explosion_Grenade"] = "Grenade",
    ["elements.explosion_StickyBomb"] = "Sticky Bomb",
    ["elements.explosion_Molotov"] = "Molotov",
    ["elements.explosion_MolotovVolatile"] = "Molotov Volatile",
    ["elements.explosion_HiOctane"] = "Hi Octane",
    ["elements.explosion_Car"] = "Car",
    ["elements.explosion_Plane"] = "Plane",
    ["elements.explosion_PetrolPump"] = "Petrol Pump",
    ["elements.explosion_DirectFlame"] = "Direct Flame",
    ["elements.explosion_WaterHydrant"] = "Water Hydrant",
    ["elements.explosion_Boat"] = "Boat",
    ["elements.explosion_BZGas"] = "BZ Gas",
    ["elements.explosion_GasCanister"] = "Gas Canister",
    ["elements.explosion_Extinguisher"] = "Extinguisher",
    ["elements.explosion_Train"] = "Train",
    ["elements.explosion_DirectFlameExplode"] = "Direct Flame Explode",
    ["elements.explosion_SmokeGrenade"] = "Smoke Grenade",
    ["elements.explosion_RedSignalBeaconRedSmoke"] = "Red Signal Beacon (Red Smoke)",
    ["elements.explosion_TorpedoUnderwater"] = "Torpedo Underwater",
    ["elements.explosion_Lantern"] = "Lantern",
    ["elements.explosion_Dynamite"] = "Dynamite",
    ["elements.explosion_DynamiteStack"] = "Dynamite Stack",
    ["elements.explosion_DynamiteVolatile"] = "Dynamite Volatile",
    ["elements.explosion_RiverBlast"] = "River Blast",
    ["elements.explosion_PlacedDynamite"] = "Placed Dynamite",
    ["elements.explosion_FireArrow"] = "Fire Arrow",
    ["elements.explosion_DynamiteArrow"] = "Dynamite Arrow",
    ["elements.explosion_PhosphorousBullet"] = "Phosphorous Bullet",
    ["elements.explosion_LightningStrike"] = "Lightning Strike",
    ["elements.explosion_TrackingArrow"] = "Tracking Arrow",
    ["elements.explosion_PoisonBottle"] = "Poison Bottle",

    -- Weather UI
    ["Weather"] = "Weather",
    ["OpenWeather"] = "Open Weather",
    ["WeatherSyncUnavailable"] = "Weather sync did not respond.",
    ["WeatherSyncLoading"] = "Syncing with weathersync…",
    ["WeatherSyncHint"] = "Ensure the weathersync resource is started.",
    ["WeatherFormDesc"] = "Adjust time, timescale, weather, wind, and sync delay. Changes sync via weathersync.",
    ["Retry"] = "Retry",
    ["Time"] = "Time",
    ["Current"] = "Current",
    ["Set"] = "Set",
    ["Apply"] = "Apply",
    ["Timescale"] = "Timescale",
    ["TransitionMs"] = "Transition (ms)",
    ["TransitionSec"] = "Transition (s)",
    ["PermanentSnow"] = "Permanent snow",
    ["Wind"] = "Wind",
    ["Direction"] = "Direction",
    ["Speed"] = "Speed",
    ["SyncDelay"] = "Sync delay",

    -- FiveM Only
    ["LandHelicopter"] = "Land Helicopter",
}

Language.de = {
    -- Search and Filtering
    ["SearchItemsPlaceholder"] = "Elemente suchen... (Strg+F)",
    ["Filters"] = "Filter",
    ["NoItemsFound"] = "Keine Elemente gefunden",
    ["TryAdjustingSearchOrFilters"] = "Suche oder Filter anpassen",
    ["LoadingItems"] = "Lade Elemente...",
    ["LoadingSettings"] = "Lade Einstellungen",

    -- Favorites
    ["NoFavorites"] = "Keine Favoriten",
    ["AddToFavorites"] = "Zu Favoriten hinzufügen",
    ["RemoveFromFavorites"] = "Aus Favoriten entfernen",
    ["FavoritesFull"] = "Favoriten voll",
    ["FavoritesFullHint"] = "Alle Favoriten-Slots sind voll. Entfernen Sie zuerst einen.",
    ["AddedToFavorites"] = "Zu Favoriten hinzugefügt",
    ["AddedToFavoritesDesc"] = "{name} zu Slot {slot} hinzugefügt",
    ["PressOrClickToSelect"] = "Drücken Sie {label} oder klicken Sie, um auszuwählen",
    ["FavoriteEmptyHint"] = "Hotkey drücken",
    ["WhileHoveringAnItem"] = "beim Hover über ein Element",
    
    -- Grid and Items
    ["GridTooltipHint"] = "Links: Auswählen für Spawn • Rechts: Optionen",
    ["QuickSpawn"] = "Schnell-Spawn",
    ["ChooseVariant"] = "Variante wählen...",
    ["ShowDetails"] = "Details anzeigen",
    ["BaseModel"] = "Basismodell",
    ["ChooseVariantTitle"] = "Variante wählen",
    ["SelectVariantToSpawn"] = "Wählen Sie eine Variante zum Spawnen",
    ["VariantsAvailable"] = "{count} Variante(n) verfügbar",

    -- Item Actions
    ["Selected"] = "Ausgewählt",
    ["SelectedDesc"] = "{name} ausgewählt - Klicken Sie in der Welt zum Spawnen",
    ["Spawned"] = "Gespawnt",
    ["SpawnedDesc"] = "{name} erfolgreich gespawnt",
    ["Deselected"] = "Abgewählt",
    ["ItemDeselected"] = "Element abgewählt",
    ["Error"] = "Fehler",
    ["FailedToSpawn"] = "Fehler beim Spawnen des Elements",
    ["FailedToAddToFavorites"] = "Fehler beim Hinzufügen zu Favoriten",
    ["FailedToUpdateFavorites"] = "Fehler beim Aktualisieren der Favoriten",
    ["FailedToLoadCategories"] = "Fehler beim Laden der Kategorien",
    ["FailedToLoadItems"] = "Fehler beim Laden der Elemente",
    ["FailedToSaveSettings"] = "Fehler beim Speichern der Einstellungen",

    --Selection Options
    ["SelectionMode"] = "Auswahlmodus",
    ["ExcludeHorsesVehicles"] = "Fahrzeuge ausschließen",
    ["ExcludePeds"] = "Peds ausschließen",
    ["IncludeObjects"] = "Objekte einbeziehen",

    -- Spawn Options
    ["SpawnMode"] = "Spawn-Modus",
    ["SpawnOnHorse"] = "Auf Pferd spawnen",
    ["SpawnAsAmbient"] = "Als Ambient spawnen",

    -- Walk Options
    ["WalkMode"] = "Gehen",
    ["Running"] = "Laufen",
    ["UsePathfindingAsDefault"] = "Wegfindung als Standard",

    -- Settings
    ["Settings"] = "Einstellungen",
    ["Appearance"] = "Aussehen",
    ["Theme"] = "Thema",
    ["Dark"] = "Dunkel",
    ["HighContrast"] = "Hoher Kontrast",
    ["Auto"] = "Auto",
    ["GridSize"] = "Rastergröße",
    ["Small"] = "Klein",
    ["Medium"] = "Mittel",
    ["Large"] = "Groß",

    ["Behavior"] = "Verhalten",
    ["ContextMenuItems"] = "Kontextmenü-Elemente",
    ["AutoSave"] = "Auto Speichern",
    ["AutoSaveHint"] = "Favoriten und Einstellungen automatisch speichern",
    ["ShowTooltips"] = "Tooltips anzeigen",
    ["ShowTooltipsHint"] = "Hilfreiche Tooltips beim Hover anzeigen",
    ["SoundEffects"] = "Soundeffekte",
    ["SoundEffectsHint"] = "Töne für Aktionen abspielen",
    ["SoundVolume"] = "Soundlautstärke",
    ["ShowPedDetails"] = "Ped-Details anzeigen",
    ["ShowPedDetailsHint"] = "Ein kompaktes Info-Panel anzeigen, wenn ein Ped ausgewählt ist",
    ["PedDetailsSize"] = "Ped-Details-Größe",

    ["CameraModeToggle"] = "Kamera-Modus umschalten",
    ["CameraModeToggleHint"] = "MMB einmal drücken, um Kameradrehung zu starten, erneut drücken zum Stoppen (anstatt halten)",

    ["ShadowPeds"] = "Schatten-Peds",
    ["ShadowPedsHint"] = "Schatten-Ped beim Spawnen anzeigen",

    -- UI Actions
    ["Reset"] = "Zurücksetzen",
    ["Cancel"] = "Abbrechen",
    ["Save"] = "Speichern",
    ["Clear"] = "Löschen",
    ["GotIt"] = "Verstanden!",
    ["LeaveGamemaster"] = "Gamemaster-Modus verlassen?",
    ["LeaveGamemasterHint"] = "Du kannst den Gamemaster-Modus mit dem Befehl jederzeit wieder aktivieren.",
    ["Confirm"] = "Bestätigen",

    -- Languages
    ["Language"] = "Sprache",
    ["English"] = "Englisch",
    ["German"] = "Deutsch",
    ["French"] = "Französisch",

    -- Help and UI
    ["HelpAndGuide"] = "Hilfe & Anleitung",
    ["Minimize"] = "Minimieren",
    ["Maximize"] = "Maximieren",
    ["Close"] = "Schließen",
    ["Back"] = "Zurück",
    ["Next"] = "Weiter",
    ["Previous"] = "Zurück",

    -- Network and Status
    ["NetworkedEntitiesInUse"] = "Networked Entities in Verwendung. Über 90 birgt Performance-Risiko; harte Grenze ~110.",
    ["LoadingNetworkUsage"] = "Lade Netzwerknutzung…",

    -- Categories and Filters
    ["Faction"] = "Fraktion",
    ["Weapon"] = "Waffe",
    ["BehaviorFilter"] = "Verhalten",
    ["Gender"] = "Geschlecht",
    ["Male"] = "Männlich",
    ["Female"] = "Weiblich",
    ["Animals"] = "Tiere",
    ["Lawman"] = "Gesetzeshüter",
    ["Criminal"] = "Krimineller",
    ["Neutral"] = "Neutral",
    ["Armed"] = "Bewaffnet",
    ["Unarmed"] = "Unbewaffnet",
    ["Melee"] = "Nahkampf",
    ["Friendly"] = "Freundlich",
    ["Hostile"] = "Feindselig",
    ["Horses"] = "Pferde",
    ["Wild"] = "Wild",
    ["Domestic"] = "Haus",
    ["Aquatic"] = "Wasser",
    ["Birds"] = "Vögel",
    ["Dangerous"] = "Gefährlich",

        -- Radial Menu
    ["BindAction"] = "Aktion binden",
    ["RemoveBinding"] = "Bindung entfernen",

    -- Help Content
    ["GettingStarted"] = "Erste Schritte",
    ["SpawningItems"] = "Elemente spawnen",
    ["KeyboardShortcuts"] = "Tastenkürzel",
    ["AdvancedFeatures"] = "Erweiterte Funktionen",
    ["AboutGmHotbar"] = "Über DD GM",
    ["Favorites"] = "Favoriten",
    ["ClickSelectThenSpawn"] = "Mit Linksklick Element auswählen; dann in der Welt klicken zum Spawnen",
    ["RightClickOptionsVariants"] = "Rechtsklick auf ein Element für Optionen und Varianten",
    ["SearchBarHint"] = "Nutzen Sie Suche und Filter, um Elemente zu finden",
    ["DragToFavorites"] = "Ziehen Sie Elemente aus dem Raster in die 1–9 Slots",
    ["PressDigitsSelectFavorite"] = "Drücken Sie 1–9, um einen Favoriten zu wählen",
    ["PressDigitsAssignFavorite"] = "Drücken Sie 1–9 beim Überfahren eines Elements, um es einem Slot zuzuweisen",
    ["CategoriesAndFilters"] = "Kategorien und Filter",
    ["SwitchCategories"] = "Zwischen Kategorien wechseln",
    ["UseFiltersToNarrow"] = "Filter verwenden, um Ergebnisse einzugrenzen",
    ["ResetClearsFiltersSearch"] = "Zurücksetzen löscht alle Filter und die Suche",
    ["CameraControls"] = "Kamera-Steuerung",
    ["Move"] = "Bewegen",
    ["UpDown"] = "Hoch / Runter",
    ["Sprint"] = "Sprinten",
    ["Zoom"] = "Zoom",
    ["ZoomWheel"] = "Mausrad",
    ["RotateCamera"] = "Kamera drehen",
    ["Yaw"] = "Gieren",
    ["Pitch"] = "Neigen",
    ["Or"] = "oder",
    ["SelectionActions"] = "Auswahl & Aktionen",
    ["SelectEntity"] = "Entität unter dem Cursor auswählen",
    ["BoxSelect"] = "Rahmenauswahl (ziehen)",
    ["OpenContextMenu"] = "Kontextmenü öffnen",
    ["MoveOrder"] = "Bewegungsbefehl mit Auswahl",
    ["ReturnSelectMode"] = "Auswahl aufheben/ Leave GM Mode",
    ["CancelSpawnMode"] = "Spawn-Modus abbrechen",
    ["CopySelection"] = "Auswahl kopieren",
    ["PasteAtCursor"] = "An Cursor einfügen",
    ["CutSelection"] = "Auswahl ausschneiden",
    ["DeleteSelection"] = "Auswahl löschen",
    ["VariantsHint"] = "Viele Elemente haben Varianten (kleiner Punkt). Rechtsklick zum Auswählen.",
    ["VariantsWeapons"] = "Verschiedene Waffen-Ausrüstungen für NPCs",
    ["VariantsColors"] = "Farbvarianten für Objekte",
    ["VariantsPresets"] = "Modifizierte Presets mit unterschiedlichen Parametern",
    ["SmartSearchHint"] = "Die Suche ist entprellt und durchsucht Namen und Tags:",
    ["SmartSearchExampleLawman"] = "findet Gesetzeshüter",
    ["SmartSearchExampleMale"] = "findet männliche NPCs",
    ["ActivityLogHint"] = "Der Log-Drawer zeichnet Aktionen auf, mit Filter und Export. Nützlich zum Debuggen oder für Rückblick.",
    ["MarqueeSelection"] = "Rahmenauswahl",
    ["MarqueeSelectionHint"] = "Ziehen Sie mit der linken Maustaste im leeren Raum, um mehrere Entitäten zu markieren.",
    ["PedInfoPanel"] = "NPC-Info-Panel",
    ["PedInfoPanelHint"] = "Bei genau einem ausgewählten NPC zeigt ein Panel Modell, LP, Waffe, Beziehung und Besitz an.",
    ["Integrated"] = "Integriert",
    ["Active"] = "Aktiv",
    ["LocalStorageAndServer"] = "Lokaler Speicher + Server",
    ["AboutIntegrationNote"] = "Diese UI ist über NUI mit dem Lua-Kern integriert. Spawns, Auswahl und Befehle funktionieren im Spiel. Favoriten werden pro Charakter gespeichert, wenn verfügbar; ansonsten lokal.",
    ["Navigation"] = "Navigation",
    ["FocusSearch"] = "Suche fokussieren",
    ["PreviousPage"] = "Vorherige Seite",
    ["NextPage"] = "Nächste Seite",
    ["CloseOverlays"] = "Overlays schließen",
    ["SpawnFavorite"] = "Favorit spawnen",
    ["ItemVariants"] = "Element-Varianten",
    ["SmartSearch"] = "Intelligente Suche",
    ["ActivityLog"] = "Aktivitätsprotokoll",
    ["RedmGamemasterTool"] = "DD Gamemaster",
    ["IntegrationStatus"] = "Integrationsstatus",
    ["TechnicalDetails"] = "Technische Details",
    ["ApiStatus"] = "API Status",
    ["NuiEvents"] = "NUI Events",
    ["DataPersistence"] = "Datenpersistenz",
    ["LocalStorage"] = "Lokaler Speicher",
    ["Framework"] = "Framework",
    ["Styling"] = "Styling",
    ["UiComponents"] = "UI Komponenten",
    ["RedmGamemasterToolDesc"] = "Dieses Hotbar-Interface bietet schnellen Zugriff auf das Spawnen von NPCs, Objekten, Fahrzeugen und das Verwalten von Szenarien in Ihrem Roleplay-Server. Mit einem Fokus auf Effizienz und Benutzerfreundlichkeit für Game-Master und Administratoren.",
    ["DevelopedBy"] = "Entwickelt von",
    ["License"] = "Lizenz",
    ["Version"] = "Version",
    ["TabSelection"] = "Alle NPCs hervorheben",
    ["OpenTutorial"] = "Tutorial öffnen",
    ["SelectFavorite"] = "Favorit auswählen",
    ["DLCStatus"] = "DLC Status",
    ["DLCStatusDesc"] = "Aktuell kein DLC verfügbar.",

    -- Ped Detail Panel
    ["SelectionDetails"] = "Auswahldetails ({count})",
    ["Entity"] = "Entität",
    ["EntityID"] = "ID {id}",
    ["Health"] = "Gesundheit",
    ["Follow"] = "Folgen",
    ["Hold"] = "Stop",
    ["AttackOnSight"] = "Bei Sicht angreifen",
    ["FollowSingleOnly"] = "Folgen (nur einzeln)",
    ["HoldPosition"] = "Position halten",
    ["AttackOnSightCapital"] = "Bei Sicht angreifen",
    ["GroupSettings"] = "Gruppeneinstellungen",
    ["PedSettings"] = "NPC-Einstellungen",
    ["AttackOnSightLabel"] = "Bei Sicht angreifen",
    ["None"] = "Keine",
    ["PlayersOnly"] = "Nur Spieler",
    ["Everyone"] = "Jeder",
    ["CannotFlee"] = "Kann nicht fliehen",
    ["AttackRange"] = "Angriffsreichweite",
    ["Meters"] = "m",
    ["ShootingAccuracy"] = "Schießgenauigkeit",
    ["Percent"] = "%",
    ["Groups"] = "Gruppen",
    ["GroupsWithCount"] = "Gruppen ({count} Entitäten)",
    ["AllInGroup"] = "Alle in: {name}",
    ["NoGroupsYet"] = "Noch keine Gruppen",
    ["NewGroupName"] = "Neuer Gruppenname...",
    ["Remove"] = "Entfernen",

    -- Groups Panel
    ["GroupsCount"] = "{count} Gruppe(n)",
    ["NewGroup"] = "+ Neue Gruppe",
    ["Members"] = "Mitglieder",
    ["NoGroupsCreated"] = "Keine Gruppen erstellt",
    ["CreateFirstGroup"] = "Erstelle deine erste Gruppe, um zu beginnen",
    ["MembersCount"] = "{count} Mitglied(er)",
    ["Creator"] = "Ersteller: {owner}",
    ["SelectAll"] = "Alle auswählen",
    ["SelectGroupToViewMembers"] = "Wähle eine Gruppe aus, um Mitglieder zu sehen",
    ["NoMembersInGroup"] = "Keine Mitglieder in dieser Gruppe",
    ["AddEntitiesToGetStarted"] = "Füge Entitäten hinzu, um zu beginnen",
    ["GroupName"] = "Gruppenname...",

    -- Context Menu Strings
    ["GoToDirect"] = "Direkt gehen",
    ["GoToPathfinding"] = "Mit Wegfindung gehen",
    ["GoToAndStand"] = "Gehen und stehen",
    ["GoToMenu"] = "Gehe zu...",
    ["AttackTarget"] = "Ziel angreifen",
    ["AttackInArea"] = "Im Bereich angreifen",
    ["AttackMenu"] = "Angreifen...",
    ["ScenariosMenu"] = "Szenarien...",
    ["StandStill"] = "Still stehen",
    ["BehaveAsAmbient"] = "NPC Verhalten aktivieren",
    ["FollowPed"] = "Folgen",
    ["StopFollowing"] = "Folgen stoppen",
    ["GiveWeaponMenu"] = "Waffe geben...",
    ["RemoveWeapon"] = "Waffe entfernen",
    ["Dismount"] = "Absteigen",
    ["Revive"] = "Wiederbeleben",
    ["HealToFull"] = "Vollständig heilen",
    ["Kill"] = "Töten",
    ["EnableGodmode"] = "Godmodus aktivieren",
    ["DisableGodmode"] = "Godmodus deaktivieren",
    ["Freeze"] = "Einfrieren",
    ["Unfreeze"] = "Auftauen",
    ["CancelAllTasks"] = "Alle Aufgaben abbrechen",
    ["ClearTasksImmediately"] = "Aufgaben sofort löschen",
    ["PedActionsMenu"] = "Charakter-Aktionen...",
    ["AnimationsMenu"] = "Animationen...",
    ["RideHorse"] = "Pferd reiten",
    ["UnmountAllPassengers"] = "Alle Passagiere absitzen lassen",
    ["DisableVehicle"] = "Fahrzeug deaktivieren",
    ["EnterVehicle"] = "Fahrzeug betreten",
    ["EnterVehicleAll"] = "Fahrzeug betreten (Alle)",
    ["UseScenario"] = "Szenario verwenden",
    ["UseNearestScenarioWalk"] = "Nächstes Szenario nutzen",
    ["UseNearestScenarioWarp"] = "Nächstes Szenario nutzen (warp)",

    -- UI and Navigation
    ["OpenSettings"] = "Einstellungen öffnen",
    ["OpenLog"] = "Protokoll öffnen",
    ["OpenHelp"] = "Hilfe öffnen",
    ["RemoveFromFavorites"] = "Aus Favoriten entfernen",
    ["EmptySlot"] = "Leerer Slot",
    ["Previous"] = "Zurück",
    ["Next"] = "Weiter",
    ["PageOf"] = "Seite {current} von {total}",
    ["ItemsTotal"] = "({count} Elemente gesamt)",
    ["Details"] = "Details",
    ["Clear"] = "Löschen",
    ["EntriesCount"] = "{filtered} von {total} Einträgen",
    ["NoLogsYet"] = "Noch keine Protokolle",
    ["ActivityWillAppearHere"] = "Aktivitäten werden hier angezeigt",
    ["NoLogsMatchFilter"] = "Keine Protokolle entsprechen dem Filter",
    ["TryAdjustingSearchOrFilter"] = "Versuchen Sie, die Suche oder den Typfilter anzupassen",
    ["SelectedPed"] = "Ausgewählter NPC",
    ["Model"] = "Modell",
    ["Hash"] = "Hash",
    ["HP"] = "LP",
    ["Weapon"] = "Waffe",
    ["Relationship"] = "Beziehung",
    ["CanAttack"] = "Kann angreifen",
    ["Yes"] = "Ja",
    ["No"] = "Nein",
    ["Prop"] = "Gegenstand",
    ["Holstered"] = "im Holster",
    ["Unarmed"] = "keine",

    -- Selection/Clipboard
    ["SelectedUnits"] = "Ausgewählt: {count}",
    ["Copied"] = "Kopiert",
    ["CopiedSelectionDesc"] = "{count} ausgewählte Ped(s) kopiert",
    ["Pasted"] = "Eingefügt",
    ["PastedSelectionDesc"] = "{count} Ped(s) eingefügt",
    ["Cut"] = "Ausschneiden",
    ["CutSelectionDesc"] = "{peds} Ped(s) ausgeschnitten",

    -- Network Pool Warning
    ["NotifyHighNetworkPoolTitle"] = "Netzwerk-Pool-Warnung",
    ["NotifyHighNetworkPoolText"] = "Hohe Anzahl an NPCs: %s/110. Reduzieren Sie die Anzahl der gespawnten Entitäten.",

    -- Impersonate
    ["Impersonate"] = "Schlüpfe in diesem NPC",
    ["StopImpersonating"] = "Verwandle dich zurück zu deinem Charakter",

    -- Object Placement Mode
    ["object_placement.title"] = "Objektplatzierung",
    ["object_placement.free_move"] = "• LMB: Achse ziehen zum Bewegen",
    ["object_placement.snap_ground"] = "• G: Am Boden ausrichten",
    ["object_placement.toggle_rotate"] = "• TAB: Drehen umschalten",
    ["object_placement.drag_rotate"] = "• LMB: Ring ziehen zum Drehen",
    ["object_placement.toggle_translate"] = "• TAB: Verschieben umschalten",
    ["object_placement.confirm_cancel"] = "• Enter: Bestätigen • RMB: Abbrechen",

    -- Object Modification Mode
    ["object_modification.title"] = "Objekt modifizieren",
    ["object_modification.start_modifying"] = "• Enter: Modifizieren starten",
    ["object_modification.start_modifying_warning"] = "• Hinweis: Nicht vernetzte Objekte werden nicht synchronisiert!",

    -- Elements DLC
    ["elements.Elements"] = "Elemente",
    ["ElementsDLC"] = "Elemente DLC",
    ["elements.CreateFire"] = "Feuer erstellen",
    ["elements.DeleteFires"] = "Feuer löschen",
    ["elements.LightningStrike"] = "Blitzeinschlag",
    ["elements.Explosions"] = "Explosionen",
    ["elements.explosion_Grenade"] = "Granate",
    ["elements.explosion_StickyBomb"] = "Haftbombe",
    ["elements.explosion_Molotov"] = "Molotow",
    ["elements.explosion_MolotovVolatile"] = "Molotow flüchtig",
    ["elements.explosion_HiOctane"] = "Hi-Oktan",
    ["elements.explosion_Car"] = "Auto",
    ["elements.explosion_Plane"] = "Flugzeug",
    ["elements.explosion_PetrolPump"] = "Tankstelle",
    ["elements.explosion_DirectFlame"] = "Direkte Flamme",
    ["elements.explosion_WaterHydrant"] = "Wasserhydrant",
    ["elements.explosion_Boat"] = "Boot",
    ["elements.explosion_BZGas"] = "BZ-Gas",
    ["elements.explosion_GasCanister"] = "Gaskartusche",
    ["elements.explosion_Extinguisher"] = "Feuerlöscher",
    ["elements.explosion_Train"] = "Zug",
    ["elements.explosion_DirectFlameExplode"] = "Direkte Flamme Explosion",
    ["elements.explosion_SmokeGrenade"] = "Rauchgranate",
    ["elements.explosion_RedSignalBeaconRedSmoke"] = "Rotes Signal (roter Rauch)",
    ["elements.explosion_TorpedoUnderwater"] = "Torpedo Unterwasser",
    ["elements.explosion_Lantern"] = "Laterne",
    ["elements.explosion_Dynamite"] = "Dynamit",
    ["elements.explosion_DynamiteStack"] = "Dynamitstapel",
    ["elements.explosion_DynamiteVolatile"] = "Dynamit flüchtig",
    ["elements.explosion_RiverBlast"] = "Fluss-Explosion",
    ["elements.explosion_PlacedDynamite"] = "Platziertes Dynamit",
    ["elements.explosion_FireArrow"] = "Feuerpfeil",
    ["elements.explosion_DynamiteArrow"] = "Dynamitpfeil",
    ["elements.explosion_PhosphorousBullet"] = "Phosphorkugel",
    ["elements.explosion_LightningStrike"] = "Blitzeinschlag",
    ["elements.explosion_TrackingArrow"] = "Spürpfeil",
    ["elements.explosion_PoisonBottle"] = "Giftflasche",

    -- Weather UI
    ["Weather"] = "Wetter",
    ["OpenWeather"] = "Wetter öffnen",
    ["WeatherSyncUnavailable"] = "Wetter-Sync hat nicht geantwortet.",
    ["WeatherSyncLoading"] = "Synchronisiere mit weathersync…",
    ["WeatherSyncHint"] = "Stelle sicher, dass die weathersync-Ressource gestartet ist.",
    ["WeatherFormDesc"] = "Zeit, Zeitskala, Wetter, Wind und Sync-Verzögerung anpassen. Änderungen synchronisieren über weathersync.",
    ["Retry"] = "Erneut versuchen",
    ["Time"] = "Zeit",
    ["Current"] = "Aktuell",
    ["Set"] = "Setzen",
    ["Apply"] = "Anwenden",
    ["Timescale"] = "Zeitskala",
    ["TransitionMs"] = "Übergang (ms)",
    ["TransitionSec"] = "Übergang (s)",
    ["PermanentSnow"] = "Dauerhafter Schnee",
    ["Wind"] = "Wind",
    ["Direction"] = "Richtung",
    ["Speed"] = "Geschwindigkeit",
    ["SyncDelay"] = "Sync-Verzögerung",

    -- FiveM Only
    ["LandHelicopter"] = "Helicopter landen",
}

Language.fr = {
    -- Search and Filtering
    ["SearchItemsPlaceholder"] = "Rechercher des items... (Ctrl+F)",
    ["Filters"] = "Filtres",
    ["NoItemsFound"] = "Aucun item trouvé",
    ["TryAdjustingSearchOrFilters"] = "Essayez d'ajuster votre recherche ou vos filtres",
    ["LoadingItems"] = "Chargement des items...",
    ["LoadingSettings"] = "Chargement des paramètres",

    -- Favorites
    ["NoFavorites"] = "Aucun favori",
    ["AddToFavorites"] = "Ajouter aux favoris",
    ["RemoveFromFavorites"] = "Retirer des favoris",
    ["FavoritesFull"] = "Favoris pleins",
    ["FavoritesFullHint"] = "Tous les emplacements de favoris sont pleins. Retirez-en un d'abord.",
    ["AddedToFavorites"] = "Ajouté aux favoris",
    ["AddedToFavoritesDesc"] = "{name} ajouté à l'emplacement {slot}",
    ["PressOrClickToSelect"] = "Appuyez sur {label} ou cliquez pour sélectionner",
    ["FavoriteEmptyHint"] = "Appuyez",
    ["WhileHoveringAnItem"] = "en survolant un item",

    -- Grid and Items
    ["GridTooltipHint"] = "Clic gauche : Sélectionner pour spawn • Clic droit : Options",
    ["QuickSpawn"] = "Spawn rapide",
    ["ChooseVariant"] = "Choisir une variante...",
    ["ShowDetails"] = "Afficher les détails",
    ["BaseModel"] = "Modèle de base",
    ["ChooseVariantTitle"] = "Choisir une variante",
    ["SelectVariantToSpawn"] = "Sélectionnez une variante à spawn",
    ["VariantsAvailable"] = "{count} variante(s) disponible(s)",

    -- Item Actions
    ["Selected"] = "Sélectionné",
    ["SelectedDesc"] = "{name} sélectionné - Cliquez dans le monde pour spawn",
    ["Spawned"] = "Spawné",
    ["SpawnedDesc"] = "{name} spawné avec succès",
    ["Deselected"] = "Désélectionné",
    ["ItemDeselected"] = "Item désélectionné",
    ["Error"] = "Erreur",
    ["FailedToSpawn"] = "Échec du spawn de l'item",
    ["FailedToAddToFavorites"] = "Échec de l'ajout aux favoris",
    ["FailedToUpdateFavorites"] = "Échec de la mise à jour des favoris",
    ["FailedToLoadCategories"] = "Échec du chargement des catégories",
    ["FailedToLoadItems"] = "Échec du chargement des items",
    ["FailedToSaveSettings"] = "Échec de la sauvegarde des paramètres",

    --Selection Options
    ["SelectionMode"] = "Mode de sélection",
    ["ExcludeHorsesVehicles"] = "Exclure les véhicules",
    ["ExcludePeds"] = "Exclure les Peds",
    ["IncludeObjects"] = "Inclure les objets",

    -- Spawn Options
    ["SpawnMode"] = "Mode de spawn",
    ["SpawnOnHorse"] = "Spawn sur cheval",
    ["SpawnAsAmbient"] = "Spawn en ambient",

    -- Walk Options
    ["WalkMode"] = "Mode de marche",
    ["Running"] = "Course",
    ["UsePathfindingAsDefault"] = "Utiliser le pathfinding par défaut",

    -- Settings
    ["Settings"] = "Paramètres",
    ["Appearance"] = "Apparence",
    ["Theme"] = "Thème",
    ["Dark"] = "Sombre",
    ["HighContrast"] = "Haut contraste",
    ["Auto"] = "Auto",
    ["GridSize"] = "Taille du HUD",
    ["Small"] = "Petit",
    ["Medium"] = "Moyen",
    ["Large"] = "Grand",

    ["Behavior"] = "Comportement",
    ["ContextMenuItems"] = "Items du menu contextuel",
    ["AutoSave"] = "Sauvegarde auto",
    ["AutoSaveHint"] = "Sauvegarder automatiquement les favoris et paramètres",
    ["ShowTooltips"] = "Afficher les tooltips",
    ["ShowTooltipsHint"] = "Afficher des tooltips utiles au survol",
    ["SoundEffects"] = "Effets sonores",
    ["SoundEffectsHint"] = "Jouer des sons pour les actions",
    ["SoundVolume"] = "Volume sonore",
    ["ShowPedDetails"] = "Afficher les détails des Peds",
    ["ShowPedDetailsHint"] = "Afficher un panneau d'info compact quand un ped est sélectionné",
    ["PedDetailsSize"] = "Taille des détails des Peds",

    ["CameraModeToggle"] = "Mode caméra bascule",
    ["CameraModeToggleHint"] = "Appuyez une fois sur MMB pour démarrer la rotation caméra, appuyez à nouveau pour arrêter (au lieu de maintenir)",

    ["ShadowPeds"] = "Peds fantômes",
    ["ShadowPedsHint"] = "Afficher un aperçu fantôme du ped pendant le spawn",

    -- UI Actions
    ["Reset"] = "Réinitialiser",
    ["Cancel"] = "Annuler",
    ["Save"] = "Sauvegarder",
    ["Clear"] = "Effacer",
    ["GotIt"] = "Compris !",
    ["LeaveGamemaster"] = "Quitter le mode Gamemaster ?",
    ["LeaveGamemasterHint"] = "Vous pouvez le réactiver avec la commande à nouveau.",
    ["Confirm"] = "Confirmer",

    -- Languages
    ["Language"] = "Langue",
    ["English"] = "Anglais",
    ["German"] = "Allemand",
    ["French"] = "Français",

    -- Help and UI
    ["HelpAndGuide"] = "Aide et guide",
    ["Minimize"] = "Réduire",
    ["Maximize"] = "Agrandir",
    ["Close"] = "Fermer",
    ["Back"] = "Retour",
    ["Next"] = "Suivant",
    ["Previous"] = "Précédent",

    -- Network and Status
    ["NetworkedEntitiesInUse"] = "Entités networkées en cours d'utilisation. Au-dessus de 90 risque les performances ; limite dure ~110.",
    ["LoadingNetworkUsage"] = "Chargement de l'utilisation réseau…",

    -- Categories and Filters
    ["Faction"] = "Faction",
    ["Weapon"] = "Arme",
    ["BehaviorFilter"] = "Comportement",
    ["Gender"] = "Genre",
    ["Male"] = "Homme",
    ["Female"] = "Femme",
    ["Animals"] = "Animaux",
    ["Lawman"] = "Homme de loi",
    ["Criminal"] = "Criminel",
    ["Neutral"] = "Neutre",
    ["Armed"] = "Armé",
    ["Unarmed"] = "Désarmé",
    ["Melee"] = "Mêlée",
    ["Friendly"] = "Amical",
    ["Hostile"] = "Hostile",
    ["Horses"] = "Chevaux",
    ["Wild"] = "Sauvage",
    ["Domestic"] = "Domestique",
    ["Aquatic"] = "Aquatique",
    ["Birds"] = "Oiseaux",
    ["Dangerous"] = "Dangereux",

    -- Radial Menu
    ["BindAction"] = "Lier une action",
    ["RemoveBinding"] = "Retirer la liaison",

    -- Help Content
    ["GettingStarted"] = "Premiers pas",
    ["SpawningItems"] = "Spawning d'items",
    ["KeyboardShortcuts"] = "Raccourcis clavier",
    ["AdvancedFeatures"] = "Fonctionnalités avancées",
    ["AboutGmHotbar"] = "À propos de DD GM",
    ["Favorites"] = "Favoris",
    ["ClickSelectThenSpawn"] = "Clic gauche sur un item pour sélectionner ; puis cliquez dans le monde pour spawn",
    ["RightClickOptionsVariants"] = "Clic droit sur un item pour les options et variantes",
    ["SearchBarHint"] = "Utilisez la barre de recherche et les filtres pour trouver des items",
    ["DragToFavorites"] = "Glissez les items de la grille vers les emplacements 1–9 ci-dessous",
    ["PressDigitsSelectFavorite"] = "Appuyez sur 1–9 pour sélectionner un favori",
    ["PressDigitsAssignFavorite"] = "Appuyez sur 1–9 en survolant un item pour l'assigner à un emplacement",
    ["CategoriesAndFilters"] = "Catégories et filtres",
    ["SwitchCategories"] = "Basculer entre les catégories",
    ["UseFiltersToNarrow"] = "Utilisez les filtres pour affiner les résultats",
    ["ResetClearsFiltersSearch"] = "Le bouton Reset efface tous les filtres et la recherche",
    ["CameraControls"] = "Contrôles de caméra",
    ["Move"] = "Déplacer",
    ["UpDown"] = "Haut / Bas",
    ["Sprint"] = "Sprint",
    ["Zoom"] = "Zoom",
    ["ZoomWheel"] = "Molette de la souris",
    ["RotateCamera"] = "Tourner la caméra",
    ["Yaw"] = "Lacet",
    ["Pitch"] = "Tangage",
    ["Or"] = "ou",
    ["SelectionActions"] = "Sélection et actions",
    ["SelectEntity"] = "Sélectionner l'entité sous le curseur",
    ["BoxSelect"] = "Sélection en boîte (glisser)",
    ["OpenContextMenu"] = "Ouvrir le menu contextuel",
    ["MoveOrder"] = "Ordre de déplacement avec sélection",
    ["ReturnSelectMode"] = "Effacer la sélection / Quitter le mode GM",
    ["CancelSpawnMode"] = "Annuler le mode spawn",
    ["CopySelection"] = "Copier la sélection",
    ["PasteAtCursor"] = "Coller au curseur",
    ["CutSelection"] = "Couper la sélection",
    ["DeleteSelection"] = "Supprimer la sélection",
    ["VariantsHint"] = "Beaucoup d'items ont plusieurs variantes (petit point). Clic droit pour choisir.",
    ["VariantsWeapons"] = "Différents loadouts d'armes pour les NPCs",
    ["VariantsColors"] = "Variations de couleurs pour les objets",
    ["VariantsPresets"] = "Presets modifiés avec différents paramètres",
    ["SmartSearchHint"] = "La recherche est debounced et regarde dans les noms et tags :",
    ["SmartSearchExampleLawman"] = "trouve les NPCs de forces de l'ordre",
    ["SmartSearchExampleMale"] = "trouve les NPCs masculins",
    ["ActivityLogHint"] = "Le collecteur de log suit les actions, avec filtrage et export. Utile pour débugger ou réviser votre session.",
    ["MarqueeSelection"] = "Sélection marquee",
    ["MarqueeSelectionHint"] = "Glissez le clic gauche dans un espace vide du monde pour sélectionner plusieurs entités en boîte.",
    ["PedInfoPanel"] = "Panneau d'info Ped",
    ["PedInfoPanelHint"] = "Quand exactement un ped est sélectionné, un panneau compact affiche le modèle, HP, arme, relation et propriété.",
    ["Integrated"] = "Intégré",
    ["Active"] = "Actif",
    ["LocalStorageAndServer"] = "Stockage local + Serveur",
    ["AboutIntegrationNote"] = "Cette UI est intégrée avec le core Lua via NUI. Les spawns, sélection et ordres fonctionnent en jeu. Les favoris persistent par personnage quand disponible ; le stockage local est utilisé en fallback.",
    ["Navigation"] = "Navigation",
    ["FocusSearch"] = "Focus recherche",
    ["PreviousPage"] = "Page précédente",
    ["NextPage"] = "Page suivante",
    ["CloseOverlays"] = "Fermer les overlays",
    ["SpawnFavorite"] = "Spawn favori",
    ["ItemVariants"] = "Variantes d'items",
    ["SmartSearch"] = "Recherche intelligente",
    ["ActivityLog"] = "Log d'activité",
    ["RedmGamemasterTool"] = "Outil DD Gamemaster",
    ["IntegrationStatus"] = "Statut d'intégration",
    ["TechnicalDetails"] = "Détails techniques",
    ["ApiStatus"] = "Statut API",
    ["NuiEvents"] = "Événements NUI",
    ["DataPersistence"] = "Persistance des données",
    ["LocalStorage"] = "Stockage local",
    ["Framework"] = "Framework",
    ["Styling"] = "Style",
    ["UiComponents"] = "Composants UI",
    ["RedmGamemasterToolDesc"] = "Cette interface hotbar fournit un accès rapide au spawning de Peds, objets, véhicules et à la gestion de scénarios prédéfinis dans votre serveur Roleplay. Construit avec un focus sur l'efficacité et la facilité d'utilisation pour les game masters et administrateurs.",
    ["DevelopedBy"] = "Développé par",
    ["License"] = "Licence",
    ["Version"] = "Version",
    ["TabSelection"] = "Surligner tous les Peds",
    ["OpenTutorial"] = "Ouvrir le tutoriel",
    ["SelectFavorite"] = "Sélectionner favori",
    ["DLCStatus"] = "Statut DLC",
    ["DLCStatusDesc"] = "Actuellement aucun DLC n'est disponible.",

    -- Ped Detail Panel
    ["SelectionDetails"] = "Détails de sélection ({count})",
    ["Entity"] = "Entité",
    ["EntityID"] = "ID {id}",
    ["Health"] = "Santé",
    ["Follow"] = "Suivre",
    ["Hold"] = "Tenir",
    ["AttackOnSight"] = "Attaquer à vue",
    ["FollowSingleOnly"] = "Suivre (seulement seul)",
    ["HoldPosition"] = "Tenir position",
    ["AttackOnSightCapital"] = "Attaquer à vue",
    ["GroupSettings"] = "Paramètres de groupe",
    ["PedSettings"] = "Paramètres Ped",
    ["AttackOnSightLabel"] = "Attaquer à vue",
    ["None"] = "Aucun",
    ["PlayersOnly"] = "Joueurs seulement",
    ["Everyone"] = "Tout le monde",
    ["CannotFlee"] = "Ne peut pas fuir",
    ["AttackRange"] = "Portée d'attaque",
    ["Meters"] = "m",
    ["ShootingAccuracy"] = "Précision de tir",
    ["Percent"] = "%",
    ["Groups"] = "Groupes",
    ["GroupsWithCount"] = "Groupes ({count} entités)",
    ["AllInGroup"] = "Tous dans : {name}",
    ["NoGroupsYet"] = "Pas encore de groupes",
    ["NewGroupName"] = "Nouveau nom de groupe...",
    ["Remove"] = "Supprimer",

    -- Groups Panel
    ["GroupsCount"] = "{count} groupe(s)",
    ["NewGroup"] = "+ Nouveau groupe",
    ["Members"] = "Membres",
    ["NoGroupsCreated"] = "Aucun groupe créé",
    ["CreateFirstGroup"] = "Créez votre premier groupe pour commencer",
    ["MembersCount"] = "{count} membre(s)",
    ["Creator"] = "Créateur : {owner}",
    ["SelectAll"] = "Sélectionner tout",
    ["SelectGroupToViewMembers"] = "Sélectionnez un groupe pour voir les membres",
    ["NoMembersInGroup"] = "Aucun membre dans ce groupe",
    ["AddEntitiesToGetStarted"] = "Ajoutez des entités pour commencer",
    ["GroupName"] = "Nom du groupe...",

    -- Context Menu Strings
    ["GoToDirect"] = "Aller directement",
    ["GoToPathfinding"] = "Aller avec pathfinding",
    ["GoToAndStand"] = "Aller et rester debout",
    ["GoToMenu"] = "Aller à...",
    ["AttackTarget"] = "Attaquer la cible",
    ["AttackInArea"] = "Attaquer dans la zone",
    ["AttackMenu"] = "Attaquer...",
    ["ScenariosMenu"] = "Scénarios...",
    ["StandStill"] = "Rester immobile",
    ["BehaveAsAmbient"] = "Se comporter en ambient",
    ["FollowPed"] = "Suivre",
    ["StopFollowing"] = "Arrêter de suivre",
    ["GiveWeaponMenu"] = "Donner une arme...",
    ["RemoveWeapon"] = "Retirer l'arme",
    ["Dismount"] = "Descendre",
    ["Revive"] = "Réanimer",
    ["HealToFull"] = "Soigner complètement",
    ["Kill"] = "Tuer",
    ["EnableGodmode"] = "Activer le Godmode",
    ["DisableGodmode"] = "Désactiver le Godmode",
    ["Freeze"] = "Geler",
    ["Unfreeze"] = "Dégeler",
    ["CancelAllTasks"] = "Annuler toutes les tâches",
    ["ClearTasksImmediately"] = "Effacer les tâches immédiatement",
    ["PedActionsMenu"] = "Actions Ped...",
    ["AnimationsMenu"] = "Animations...",
    ["RideHorse"] = "Monter le cheval",
    ["UnmountAllPassengers"] = "Démonter tous les passagers",
    ["DisableVehicle"] = "Désactiver le véhicule",
    ["EnterVehicle"] = "Entrer dans le véhicule",
    ["EnterVehicleAll"] = "Entrer dans le véhicule (Tous)",
    ["UseScenario"] = "Utiliser le scénario",
    ["UseNearestScenarioWalk"] = "Utiliser le scénario le plus proche",
    ["UseNearestScenarioWarp"] = "Utiliser le scénario le plus proche (warp)",

    -- UI and Navigation
    ["OpenSettings"] = "Ouvrir les paramètres",
    ["OpenLog"] = "Ouvrir le log",
    ["OpenHelp"] = "Ouvrir l'aide",
    ["RemoveFromFavorites"] = "Retirer des favoris",
    ["EmptySlot"] = "Emplacement vide",
    ["Previous"] = "Précédent",
    ["Next"] = "Suivant",
    ["PageOf"] = "Page {current} sur {total}",
    ["ItemsTotal"] = "({count} items au total)",
    ["Details"] = "Détails",
    ["Clear"] = "Effacer",
    ["EntriesCount"] = "{filtered} sur {total} entrées",
    ["NoLogsYet"] = "Aucun log pour le moment",
    ["ActivityWillAppearHere"] = "L'activité apparaîtra ici",
    ["NoLogsMatchFilter"] = "Aucun log ne correspond à votre filtre",
    ["TryAdjustingSearchOrFilter"] = "Essayez d'ajuster votre recherche ou filtre de type",
    ["SelectedPed"] = "Ped sélectionné",
    ["Model"] = "Modèle",
    ["Hash"] = "Hash",
    ["HP"] = "HP",
    ["Weapon"] = "Arme",
    ["Relationship"] = "Relation",
    ["CanAttack"] = "Peut attaquer",
    ["Yes"] = "Oui",
    ["No"] = "Non",
    ["Prop"] = "Prop",
    ["Holstered"] = "Rengainé",
    ["Unarmed"] = "Désarmé",

    -- Selection/Clipboard
    ["SelectedUnits"] = "Sélectionnés : {count}",
    ["Copied"] = "Copié",
    ["CopiedSelectionDesc"] = "Copié {count} ped(s) sélectionné(s)",
    ["Pasted"] = "Collé",
    ["PastedSelectionDesc"] = "Collé {count} ped(s)",
    ["Cut"] = "Coupé",
    ["CutSelectionDesc"] = "Coupé {peds} ped(s){vehicles,select,0, ,1, et {vehicles} véhicule,other, et {vehicles} véhicules}",

    -- Network Pool Warning
    ["NotifyHighNetworkPoolTitle"] = "Avertissement Network Pool",
    ["NotifyHighNetworkPoolText"] = "Compteur élevé de peds networkés : %s/110. Considérez réduire les entités spawnées.",

    -- Impersonate
    ["Impersonate"] = "Usurper",
    ["StopImpersonating"] = "Arrêter l'usurpation",

    -- Object Placement Mode
    ["object_placement.title"] = "Placement d'objet",
    ["object_placement.free_move"] = "• Clic gauche : Glisser l'axe pour déplacer",
    ["object_placement.snap_ground"] = "• G : Snap au sol",
    ["object_placement.toggle_rotate"] = "• TAB : Basculer rotation",
    ["object_placement.drag_rotate"] = "• Clic gauche : Glisser l'anneau pour tourner",
    ["object_placement.toggle_translate"] = "• TAB : Basculer translation",
    ["object_placement.confirm_cancel"] = "• Entrée : Confirmer • Clic droit : Annuler",

    -- Object Modification Mode
    ["object_modification.title"] = "Modifier l'objet",
    ["object_modification.start_modifying"] = "• Entrée : Commencer la modification",
    ["object_modification.start_modifying_warning"] = "• Note : Les objets non networkés ne sont pas synchronisés !",

    -- Elements DLC
    ["elements.Elements"] = "Éléments",
    ["ElementsDLC"] = "Éléments DLC",
    ["elements.CreateFire"] = "Créer un feu",
    ["elements.DeleteFires"] = "Supprimer les feux",
    ["elements.LightningStrike"] = "Coup de foudre",
    ["elements.Explosions"] = "Explosions",
    ["elements.explosion_Grenade"] = "Grenade",
    ["elements.explosion_StickyBomb"] = "Bombe collante",
    ["elements.explosion_Molotov"] = "Molotov",
    ["elements.explosion_MolotovVolatile"] = "Molotov volatil",
    ["elements.explosion_HiOctane"] = "Hi Octane",
    ["elements.explosion_Car"] = "Voiture",
    ["elements.explosion_Plane"] = "Avion",
    ["elements.explosion_PetrolPump"] = "Pompe à essence",
    ["elements.explosion_DirectFlame"] = "Flamme directe",
    ["elements.explosion_WaterHydrant"] = "Bouche d'incendie",
    ["elements.explosion_Boat"] = "Bateau",
    ["elements.explosion_BZGas"] = "Gaz BZ",
    ["elements.explosion_GasCanister"] = "Cartouche de gaz",
    ["elements.explosion_Extinguisher"] = "Extincteur",
    ["elements.explosion_Train"] = "Train",
    ["elements.explosion_DirectFlameExplode"] = "Flamme directe explosion",
    ["elements.explosion_SmokeGrenade"] = "Grenade fumigène",
    ["elements.explosion_RedSignalBeaconRedSmoke"] = "Balise signal rouge (fumée rouge)",
    ["elements.explosion_TorpedoUnderwater"] = "Torpille sous-marine",
    ["elements.explosion_Lantern"] = "Lanterne",
    ["elements.explosion_Dynamite"] = "Dynamite",
    ["elements.explosion_DynamiteStack"] = "Pile de dynamite",
    ["elements.explosion_DynamiteVolatile"] = "Dynamite volatile",
    ["elements.explosion_RiverBlast"] = "Explosion rivière",
    ["elements.explosion_PlacedDynamite"] = "Dynamite posée",
    ["elements.explosion_FireArrow"] = "Flèche enflammée",
    ["elements.explosion_DynamiteArrow"] = "Flèche dynamite",
    ["elements.explosion_PhosphorousBullet"] = "Balle au phosphore",
    ["elements.explosion_LightningStrike"] = "Coup de foudre",
    ["elements.explosion_TrackingArrow"] = "Flèche de repérage",
    ["elements.explosion_PoisonBottle"] = "Fiole de poison",

    -- Weather UI
    ["Weather"] = "Météo",
    ["OpenWeather"] = "Ouvrir la météo",
    ["WeatherSyncUnavailable"] = "La synchro météo n'a pas répondu.",
    ["WeatherSyncLoading"] = "Synchronisation avec weathersync…",
    ["WeatherSyncHint"] = "Vérifiez que la ressource weathersync est démarrée.",
    ["WeatherFormDesc"] = "Ajuster l'heure, l'échelle de temps, la météo, le vent et le délai de sync. Les changements passent par weathersync.",
    ["Retry"] = "Réessayer",
    ["Time"] = "Heure",
    ["Current"] = "Actuel",
    ["Set"] = "Définir",
    ["Apply"] = "Appliquer",
    ["Timescale"] = "Échelle de temps",
    ["TransitionMs"] = "Transition (ms)",
    ["TransitionSec"] = "Transition (s)",
    ["PermanentSnow"] = "Neige permanente",
    ["Wind"] = "Vent",
    ["Direction"] = "Direction",
    ["Speed"] = "Vitesse",
    ["SyncDelay"] = "Délai de sync",

    -- FiveM Only
    ["LandHelicopter"] = "Atterrir l'hélicoptère",
}
