-- This file is managed automatically by FX-Doorlock.
-- Do not edit manually.
Config.Doors = {

    {
        id           = 1776116601,
        name         = "valgun1",
        locked       = true,
        lockpickable = false,
        alertLaw     = false,
        hideLock     = false,
        metalKey     = false,
        pairedDoorId = nil,
        jobs         = { "sheriff" },
        charIds      = {},
        groups       = {},
        iconOffsetX  = nil,
        iconOffsetY  = nil,
        iconOffsetZ  = nil,
        doors        = {
            { objHash = 475159788, objCoords = vector3(-283.5355, 784.4088, 118.5298), objHeading = 0.00 },
        },
    },

    {
        id           = 1778537069,
        name         = "bwbankdoor2",
        locked       = true,
        lockpickable = false,
        alertLaw     = false,
        hideLock     = false,
        metalKey     = false,
        pairedDoorId = nil,
        jobs         = {},
        charIds      = {},
        groups       = {},
        iconOffsetX  = nil,
        iconOffsetY  = nil,
        iconOffsetZ  = nil,
        doors        = {
            { objHash = 2117902999, objCoords = vector3(-816.7253, -1276.7510, 42.6412), objHeading = 0.00 },
        },
    },

    {
        id           = 1777469073,
        name         = "test555",
        locked       = true,
        lockpickable = false,
        alertLaw     = false,
        hideLock     = false,
        metalKey     = true,
        pairedDoorId = nil,
        jobs         = {},
        charIds      = {},
        groups       = {},
        iconOffsetX  = nil,
        iconOffsetY  = nil,
        iconOffsetZ  = nil,
        doors        = {
            { objHash = 3526207172, objCoords = vector3(-810.4075, -1318.5153, 42.6748), objHeading = 270.40 },
            { objHash = 3311897912, objCoords = vector3(-810.4100, -1320.7018, 42.6748), objHeading = 89.81 },
        },
    },

    {
        id           = 1778891558,
        name         = "bank1",
        locked       = true,
        lockpickable = false,
        alertLaw     = false,
        hideLock     = false,
        metalKey     = false,
        pairedDoorId = nil,
        jobs         = {},
        charIds      = {},
        groups       = {},
        iconOffsetX  = nil,
        iconOffsetY  = nil,
        iconOffsetZ  = nil,
        doors        = {
            { objHash = 531022111, objCoords = vector3(-809.1414, -1279.1899, 42.6615), objHeading = 90.14 },
        },
    },

    {
        id           = 1777468406,
        name         = "test5",
        locked       = false,
        lockpickable = false,
        alertLaw     = false,
        hideLock     = false,
        metalKey     = true,
        pairedDoorId = nil,
        jobs         = {},
        charIds      = {},
        groups       = {},
        iconOffsetX  = nil,
        iconOffsetY  = nil,
        iconOffsetZ  = nil,
        doors        = {
            { objHash = 2796645535, objCoords = vector3(-790.3033, -1323.2913, 42.9389), objHeading = 89.57 },
        },
    },

    {
        id           = 1777464975,
        name         = "test24",
        locked       = true,
        lockpickable = false,
        alertLaw     = false,
        hideLock     = false,
        metalKey     = true,
        pairedDoorId = nil,
        jobs         = { "test" },
        charIds      = {},
        groups       = {},
        iconOffsetX  = nil,
        iconOffsetY  = nil,
        iconOffsetZ  = nil,
        doors        = {
            { objHash = 1597362984, objCoords = vector3(1116.3994, 485.9919, 96.3063), objHeading = 39.67 },
        },
    },

    {
        id           = 1776041168,
        name         = "test",
        locked       = true,
        lockpickable = false,
        alertLaw     = false,
        hideLock     = false,
        metalKey     = false,
        pairedDoorId = nil,
        jobs         = {},
        charIds      = {},
        groups       = {},
        iconOffsetX  = nil,
        iconOffsetY  = nil,
        iconOffsetZ  = nil,
        doors        = {
            { objHash = 2580386965, objCoords = vector3(-755.9100, -1275.6100, 43.0500), objHeading = 91.00 },
            { objHash = 2819043592, objCoords = vector3(-755.8961, -1277.3409, 43.0500), objHeading = 90.00 },
        },
    },

}
