    -- ═══════════════════════════════════════════════════════════════
    -- QC-AdvancedMoonshine V2 - ITEMS TO ADD TO rsg-core/shared/items.lua
    -- ═══════════════════════════════════════════════════════════════
    still_build                              = { name = 'still_build',                              label = 'Moonshine Still Kit',               weight = 5000,  type = 'item',     ammotype = nil, image = 'still_build.png',                              unique = false, useable = true,  shouldClose = true, description = 'A kit for building a moonshine distillery' },
    coal_ore                                 = { name = 'coal_ore',                                 label = 'Coal',                              weight = 100,   type = 'item',     ammotype = nil, image = 'coal_ore.png',                                 unique = false, useable = false, shouldClose = true, description = 'Used as fuel for stills' },
    dynamite                                 = { name = 'dynamite',                                 label = 'Dynamite',                          weight = 500,   type = 'item',     ammotype = nil, image = 'dynamite.png',                                 unique = false, useable = true,  shouldClose = true, description = 'Explosive used for destroying stills' },
    nails                                    = { name = 'nails',                                    label = 'Nails',                             weight = 20,    type = 'item',     ammotype = nil, image = 'nails.png',                                    unique = false, useable = false, shouldClose = true, description = 'Essential component for maintaining mechanic parts' },
    bolts                                    = { name = 'bolts',                                    label = 'Bolts',                             weight = 10,    type = 'item',     ammotype = nil, image = 'bolts.png',                                    unique = false, useable = false, shouldClose = true, description = 'Metal bolts for construction' },
    bnuts                                    = { name = 'bnuts',                                    label = 'Bolt Nuts',                         weight = 10,    type = 'item',     ammotype = nil, image = 'bnuts.png',                                    unique = false, useable = false, shouldClose = true, description = 'Nuts for bolts' },
    metal_components                         = { name = 'metal_components',                         label = 'Metal Components',                  weight = 100,   type = 'item',     ammotype = nil, image = 'metal_components.png',                         unique = false, useable = false, shouldClose = true, description = 'Various metal parts for repairs and upgrades' },
    moonshine_barrel                         = { name = 'moonshine_barrel',                         label = 'Moonshine Barrel',                  weight = 2000,  type = 'item',     ammotype = nil, image = 'moonshine_barrel.png',                         unique = false, useable = false, shouldClose = true, description = 'A large barrel for fermenting mash' },
    moonshine_pot_distillery                 = { name = 'moonshine_pot_distillery',                 label = 'Distillery Pot',                    weight = 1500,  type = 'item',     ammotype = nil, image = 'moonshine_pot_distillery.png',                 unique = false, useable = false, shouldClose = true, description = 'Essential pot for distilling moonshine' },
    moonshine_pipe                           = { name = 'moonshine_pipe',                           label = 'Moonshine Pipe',                    weight = 500,   type = 'item',     ammotype = nil, image = 'moonshine_pipe.png',                           unique = false, useable = false, shouldClose = true, description = 'Copper pipe for moonshine distillation' },
    moonshine_condenser                      = { name = 'moonshine_condenser',                      label = 'Moonshine Condenser',               weight = 800,   type = 'item',     ammotype = nil, image = 'moonshine_condenser.png',                      unique = false, useable = false, shouldClose = true, description = 'Condenser coil for distilling process' },
    moonshine_empty_jug                      = { name = 'moonshine_empty_jug',                      label = 'Empty Jug',                         weight = 200,   type = 'item',     ammotype = nil, image = 'moonshine_empty_jug.png',                      unique = false, useable = false, shouldClose = true, description = 'Empty jug for storing moonshine' },
    consumable_mash                          = { name = 'consumable_mash',                          label = 'Basic Mash',                        weight = 500,   type = 'item',     ammotype = nil, image = 'consumable_mash.png',                          unique = false, useable = false, shouldClose = true, description = 'Fermented mash ready for distillation' },
    consumable_mash_alaskan                  = { name = 'consumable_mash_alaskan',                  label = 'Alaskan Mash',                      weight = 500,   type = 'item',     ammotype = nil, image = 'consumable_mash_alaskan.png',                  unique = false, useable = false, shouldClose = true, description = 'Berry-infused mash from the north' },
    consumable_mash_american                 = { name = 'consumable_mash_american',                 label = 'American Mash',                     weight = 500,   type = 'item',     ammotype = nil, image = 'consumable_mash_american.png',                 unique = false, useable = false, shouldClose = true, description = 'Classic American-style corn and wheat mash' },
    consumable_mash_apple_crumb              = { name = 'consumable_mash_apple_crumb',              label = 'Apple Crumb Mash',                  weight = 500,   type = 'item',     ammotype = nil, image = 'consumable_mash_apple_crumb.png',              unique = false, useable = false, shouldClose = true, description = 'Sweet apple and cinnamon mash' },
    consumable_mash_blackberry               = { name = 'consumable_mash_blackberry',               label = 'Blackberry Mash',                   weight = 500,   type = 'item',     ammotype = nil, image = 'consumable_mash_blackberry.png',               unique = false, useable = false, shouldClose = true, description = 'Dark berry mash with rich flavor' },
    consumable_mash_peach                    = { name = 'consumable_mash_peach',                    label = 'Peach Mash',                        weight = 500,   type = 'item',     ammotype = nil, image = 'consumable_mash_peach.png',                    unique = false, useable = false, shouldClose = true, description = 'Sweet peach-infused mash' },
    consumable_mash_plum                     = { name = 'consumable_mash_plum',                     label = 'Plum Mash',                         weight = 500,   type = 'item',     ammotype = nil, image = 'consumable_mash_plum.png',                     unique = false, useable = false, shouldClose = true, description = 'Rich plum-flavored mash' },
    consumable_mash_raspberry                = { name = 'consumable_mash_raspberry',                label = 'Raspberry Mash',                    weight = 500,   type = 'item',     ammotype = nil, image = 'consumable_mash_raspberry.png',                unique = false, useable = false, shouldClose = true, description = 'Tart raspberry mash' },
    consumable_mash_tropical_punch           = { name = 'consumable_mash_tropical_punch',           label = 'Tropical Punch Mash',               weight = 500,   type = 'item',     ammotype = nil, image = 'consumable_mash_tropical_punch.png',           unique = false, useable = false, shouldClose = true, description = 'Exotic fruit mash blend' },
    consumable_mash_wild_cider               = { name = 'consumable_mash_wild_cider',               label = 'Wild Cider Mash',                   weight = 500,   type = 'item',     ammotype = nil, image = 'consumable_mash_wild_cider.png',               unique = false, useable = false, shouldClose = true, description = 'Wild crabapple and honey mash' },
    consumable_alcohol_moonshine             = { name = 'consumable_alcohol_moonshine',             label = 'Basic Moonshine',                   weight = 300,   type = 'item',     ammotype = nil, image = 'consumable_alcohol_moonshine.png',             unique = false, useable = true,  shouldClose = true, description = 'Strong homemade moonshine' },
    consumable_moonshine_alaskan             = { name = 'consumable_moonshine_alaskan',             label = 'Alaskan Glow Moonshine',            weight = 300,   type = 'item',     ammotype = nil, image = 'consumable_moonshine_alaskan.png',             unique = false, useable = true,  shouldClose = true, description = 'Berry-flavored moonshine from the north' },
    consumable_moonshine_american            = { name = 'consumable_moonshine_american',            label = 'American Pride Moonshine',          weight = 300,   type = 'item',     ammotype = nil, image = 'consumable_moonshine_american.png',            unique = false, useable = true,  shouldClose = true, description = 'Classic American moonshine' },
    consumable_moonshine_apple_crumb         = { name = 'consumable_moonshine_apple_crumb',         label = 'Apple Pie Moonshine',               weight = 300,   type = 'item',     ammotype = nil, image = 'consumable_moonshine_apple_crumb.png',         unique = false, useable = true,  shouldClose = true, description = 'Sweet apple pie flavored moonshine' },
    consumable_moonshine_blackberry          = { name = 'consumable_moonshine_blackberry',          label = 'Blackberry Moonshine',              weight = 300,   type = 'item',     ammotype = nil, image = 'consumable_moonshine_blackberry.png',          unique = false, useable = true,  shouldClose = true, description = 'Rich blackberry moonshine' },
    consumable_moonshine_peach               = { name = 'consumable_moonshine_peach',               label = 'Peach Moonshine',                   weight = 300,   type = 'item',     ammotype = nil, image = 'consumable_moonshine_peach.png',               unique = false, useable = true,  shouldClose = true, description = 'Sweet peach moonshine' },
    consumable_moonshine_plum                = { name = 'consumable_moonshine_plum',                label = 'Plum Moonshine',                    weight = 300,   type = 'item',     ammotype = nil, image = 'consumable_moonshine_plum.png',                unique = false, useable = true,  shouldClose = true, description = 'Rich plum moonshine' },
    consumable_moonshine_raspberry           = { name = 'consumable_moonshine_raspberry',           label = 'Raspberry Moonshine',               weight = 300,   type = 'item',     ammotype = nil, image = 'consumable_moonshine_raspberry.png',           unique = false, useable = true,  shouldClose = true, description = 'Tart raspberry moonshine' },
    consumable_moonshine_tropical_punch      = { name = 'consumable_moonshine_tropical_punch',      label = 'Tropical Punch Moonshine',          weight = 300,   type = 'item',     ammotype = nil, image = 'consumable_moonshine_tropical_punch.png',      unique = false, useable = true,  shouldClose = true, description = 'Exotic tropical fruit moonshine' },
    consumable_moonshine_wild_cider          = { name = 'consumable_moonshine_wild_cider',          label = 'Wild Creek Moonshine',              weight = 300,   type = 'item',     ammotype = nil, image = 'consumable_moonshine_wild_cider.png',          unique = false, useable = true,  shouldClose = true, description = 'Wild crabapple honey moonshine' },
    consumable_yeast                         = { name = 'consumable_yeast',                         label = 'Yeast',                             weight = 50,    type = 'item',     ammotype = nil, image = 'consumable_yeast.png',                         unique = false, useable = false, shouldClose = true, description = 'Essential for fermentation' },

-- ═══════════════════════════════════════════════════════════════
-- NOTES:
-- ═══════════════════════════════════════════════════════════════
-- 1. Some items like corn, water, sugar, berries, fruits, etc.
--    are likely already in your items.lua. Check before adding!
--
-- 2. Items like nails, bolts, bnuts, metal_components may exist
--    in crafting systems. Check your existing items first!
--
-- 3. All moonshine consumables should have appropriate effects
--    in your consumables.lua or similar file
--
-- 4. Make sure to create corresponding images for all items
--    in rsg-inventory/html/images/
-- ═══════════════════════════════════════════════════════════════
