-- ─── CATEGORIES ──────────────────────────────────────────────────────────────

Config.Categories = {
    { id = "campsetup",  label = "cat_campsetup",  icon = "mdi:flag-variant"      }, -- items with createCamp = true
    { id = "shelter",    label = "cat_shelter",    icon = "mdi:tent"              },
    { id = "furniture",  label = "cat_furniture",  icon = "mdi:chair-rolling"     },
    { id = "fire",       label = "cat_fire",       icon = "mdi:campfire"          },
    { id = "lighting",   label = "cat_lighting",   icon = "game-icons:old-lantern"},
    { id = "storage",    label = "cat_storage",    icon = "mdi:treasure-chest"    },
    { id = "decoration", label = "cat_decoration", icon = "mdi:feather"           },
    { id = "utility",    label = "cat_utility",    icon = "mdi:hammer-wrench"     },
    { id = "movecamp",   label = "cat_movecamp",   icon = "game-icons:old-wagon"  },
}

-- ─── ITEMS (catalog) ─────────────────────────────────────────────────────────
-- `itemName` is the inventory key. `prop` is the world model.

Config.CampItems = {
    -- SHELTER ----------------------------------------------------------------
    { itemName = "tent_open",         id = "tent_open",        label = "item_tent_open",        prop = "s_tent_maropen01b",                    category = "shelter",    price = { cash = 13, gold = 0 }, weight = 1.0 },
    { itemName = "tent_hunter",       id = "tent_hunter",      label = "item_tent_hunter",      prop = "mp005_s_posse_tent_bountyhunter07x",   category = "shelter",    price = { cash = 17, gold = 0 }, weight = 1.0 },
    { itemName = "tent_mountain",     id = "tent_mountain",    label = "item_tent_mountain",    prop = "p_tentmountainmen02x",                 category = "shelter",    price = { cash = 16, gold = 0 }, weight = 1.0 },
    { itemName = "tent_rain",         id = "tent_rain",        label = "item_tent_rain",        prop = "s_wap_rainsfalls",                     category = "shelter",    price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "tent_tanner",       id = "tent_tanner",      label = "item_tent_tanner",      prop = "mp004_p_mptenttanner01x",              category = "shelter",    price = { cash = 15, gold = 0 }, weight = 1.0 },
    { itemName = "tent_lemoyne",      id = "tent_lemoyne",     label = "item_tent_lemoyne",     prop = "p_gangtentlemoyne01x",                 category = "shelter",    price = { cash = 14, gold = 0 }, weight = 1.0 },
    { itemName = "tent_hide_small",   id = "tent_hide_small",  label = "item_tent_hide_small",  prop = "p_ambtenthide01b",                     category = "shelter",    price = { cash = 12, gold = 0 }, weight = 1.0 },
    { itemName = "tent_bison",        id = "tent_bison",       label = "item_tent_bison",       prop = "s_tentbison01x",                       category = "shelter",    price = { cash = 18, gold = 0 }, weight = 1.0 },
    { itemName = "tent_swamp",        id = "tent_swamp",       label = "item_tent_swamp",       prop = "p_ambtentswamp01x",                    category = "shelter",    price = { cash = 10, gold = 0 }, weight = 1.0 },
    { itemName = "tent_mulch",        id = "tent_mulch",       label = "item_tent_mulch",       prop = "p_ambtentmulch01b",                    category = "shelter",    price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "shelter_leanto",    id = "shelter_leanto",   label = "item_shelter_leanto",   prop = "p_leantopine01x",                      category = "shelter",    price = { cash = 9,  gold = 0 }, weight = 1.0 },
    { itemName = "shelter_debris",    id = "shelter_debris",   label = "item_shelter_debris",   prop = "p_ambtentdebris01x",                   category = "shelter",    price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "caravan_wagon",     id = "caravan_wagon",    label = "item_caravan_wagon",    prop = "s_wagoncaravan01a",                    category = "shelter",    price = { cash = 20, gold = 0 }, weight = 1.0 },

    -- FURNITURE --------------------------------------------------------------
    { itemName = "table_wood",        id = "table_wood",       label = "item_table_wood",       prop = "p_table11x",                           category = "furniture",  price = { cash = 11, gold = 0 }, weight = 1.0 },
    { itemName = "chair_wood",        id = "chair_wood",       label = "item_chair_wood",       prop = "p_ambchair01x",                        category = "furniture",  price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "bench_wood",        id = "bench_wood",       label = "item_bench_wood",       prop = "p_bench03x",                           category = "furniture",  price = { cash = 9,  gold = 0 }, weight = 1.0 },
    { itemName = "cot",               id = "cot",              label = "item_cot",              prop = "p_cot01x",                             category = "furniture",  price = { cash = 10, gold = 0 }, weight = 1.0 },
    { itemName = "table_bespoke",     id = "table_bespoke",    label = "item_table_bespoke",    prop = "p_bespoketable01x",                    category = "furniture",  price = { cash = 14, gold = 0 }, weight = 1.0 },
    { itemName = "stool_folding",     id = "stool_folding",    label = "item_stool_folding",    prop = "p_stoolfolding01x",                    category = "furniture",  price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "chair_folding",     id = "chair_folding",    label = "item_chair_folding",    prop = "p_chairfolding02x",                    category = "furniture",  price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "chair_rustic",      id = "chair_rustic",     label = "item_chair_rustic",     prop = "p_chair09x",                           category = "furniture",  price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "bed_native_small",  id = "bed_native_small", label = "item_bed_native_small", prop = "p_bedindian02x",                       category = "furniture",  price = { cash = 10, gold = 0 }, weight = 1.0 },
    { itemName = "bed_native_large",  id = "bed_native_large", label = "item_bed_native_large", prop = "p_graveindian01x",                     category = "furniture",  price = { cash = 13, gold = 0 }, weight = 1.0 },
    { itemName = "bedroll",           id = "bedroll",          label = "item_bedroll",          prop = "p_bedrollopen03x",                     category = "furniture",  price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "backrest",          id = "backrest",         label = "item_backrest",         prop = "p_indianbackrest01x",                  category = "furniture",  price = { cash = 5,  gold = 0 }, weight = 1.0 },
    { itemName = "log_bench_large",   id = "log_bench_large",  label = "item_log_bench_large",  prop = "p_bench_log05x",                       category = "furniture",  price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "log_bench_small",   id = "log_bench_small",  label = "item_log_bench_small",  prop = "p_bench_log03x",                       category = "furniture",  price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "log_bench_medium",  id = "log_bench_medium", label = "item_log_bench_medium", prop = "p_bench_log04x",                       category = "furniture",  price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "forge",             id = "forge",            label = "item_forge",            prop = "p_forge01x",                           category = "furniture",  price = { cash = 20, gold = 0 }, weight = 1.0 },
    { itemName = "anvil",             id = "anvil",            label = "item_anvil",            prop = "p_anvil01x",                           category = "furniture",  price = { cash = 18, gold = 0 }, weight = 1.0 },
    { itemName = "anvil_stump",       id = "anvil_stump",      label = "item_anvil_stump",      prop = "p_stump",                              category = "furniture",  price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "sawhorse",          id = "sawhorse",         label = "item_sawhorse",         prop = "p_sawhorse04x",                        category = "furniture",  price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "workbench",         id = "workbench",        label = "item_workbench",        prop = "p_benchwork01x",                       category = "furniture",  price = { cash = 15, gold = 0 }, weight = 1.0 },
    { itemName = "grindstone",        id = "grindstone",       label = "item_grindstone",       prop = "p_grindingwheel01x",                   category = "furniture",  price = { cash = 14, gold = 0 }, weight = 1.0 },
    { itemName = "coal_bin",          id = "coal_bin",         label = "item_coal_bin",         prop = "p_coalbin01x",                         category = "furniture",  price = { cash = 10, gold = 0 }, weight = 1.0 },

    -- FIRE & COOKING ---------------------------------------------------------
    { itemName = "bonfire",           id = "bonfire",          label = "item_bonfire",          prop = "mp001_p_mp_finishline_bonfire01x",     category = "fire",       price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "campfire_1",        id = "campfire_1",       label = "item_campfire_1",       prop = "p_campfire01x",                        category = "fire",       price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "campfire_2",        id = "campfire_2",       label = "item_campfire_2",       prop = "p_campfire02x",                        category = "fire",       price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "campfire_3",        id = "campfire_3",       label = "item_campfire_3",       prop = "p_campfire03x",                        category = "fire",       price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "campfire_4",        id = "campfire_4",       label = "item_campfire_4",       prop = "p_campfire04x",                        category = "fire",       price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "campfire_5",        id = "campfire_5",       label = "item_campfire_5",       prop = "p_campfire05x",                        category = "fire",       price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "firepit",           id = "firepit",          label = "item_firepit",          prop = "p_cookfirestructure02x",               category = "fire",       price = { cash = 9,  gold = 0 }, weight = 1.0 },
    { itemName = "kettle_fire",       id = "kettle_fire",      label = "item_kettle_fire",      prop = "mp001_p_mp_kettle03_fire01x",          category = "fire",       price = { cash = 10, gold = 0 }, weight = 1.0 },
    { itemName = "bread_oven",        id = "bread_oven",       label = "item_bread_oven",       prop = "p_breadoven01x",                       category = "fire",       price = { cash = 16, gold = 0 }, weight = 1.0 },

    -- LIGHTING ---------------------------------------------------------------
    { itemName = "lantern_oil",       id = "lantern_oil",      label = "item_lantern_oil",      prop = "p_lantern09xint",                      category = "lighting",   price = { cash = 12, gold = 0 }, weight = 1.0 },
    { itemName = "lamp_street",       id = "lamp_street",      label = "item_lamp_street",      prop = "p_lampstreet01x",                      category = "lighting",   price = { cash = 17, gold = 0 }, weight = 1.0 },
    { itemName = "light_post",        id = "light_post",       label = "item_light_post",       prop = "p_lightpost01x",                       category = "lighting",   price = { cash = 15, gold = 0 }, weight = 1.0 },

    -- STORAGE ----------------------------------------------------------------
    { itemName = "chest_small",       id = "chest_small",      label = "item_chest_small",      prop = "s_cvan_chest01",                       category = "storage",    price = { cash = 14, gold = 0 }, weight = 1.0 },
    { itemName = "chest_large",       id = "chest_large",      label = "item_chest_large",      prop = "p_chestmedhunt01x",                    category = "storage",    price = { cash = 18, gold = 0 }, weight = 1.0 },
    { itemName = "trunk",             id = "trunk",            label = "item_trunk",            prop = "p_trunk05x",                           category = "storage",    price = { cash = 13, gold = 0 }, weight = 1.0 },
    { itemName = "barrel",            id = "barrel",           label = "item_barrel",           prop = "p_barrel02x",                          category = "storage",    price = { cash = 9,  gold = 0 }, weight = 1.0 },
    { itemName = "crate",             id = "crate",            label = "item_crate",            prop = "p_crate15x",                           category = "storage",    price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "coffin",            id = "coffin",           label = "item_coffin",           prop = "p_coffin04x_sea",                      category = "storage",    price = { cash = 15, gold = 0 }, weight = 1.0 },
    { itemName = "washbasin",         id = "washbasin",        label = "item_washbasin",        prop = "p_basinwater01x",                      category = "storage",    price = { cash = 11, gold = 0 }, weight = 1.0 },
    { itemName = "dirt_tub",          id = "dirt_tub",         label = "item_dirt_tub",         prop = "p_dirttub01x",                         category = "storage",    price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "rope_basket",       id = "rope_basket",      label = "item_rope_basket",      prop = "p_basketrope01x",                      category = "storage",    price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "water_bucket",      id = "water_bucket",     label = "item_water_bucket",     prop = "p_waterbucket01x",                     category = "storage",    price = { cash = 5,  gold = 0 }, weight = 1.0 },
    { itemName = "grain_sack_a",      id = "grain_sack_a",     label = "item_grain_sack_a",     prop = "p_sandbagcover01x",                    category = "storage",    price = { cash = 5,  gold = 0 }, weight = 1.0 },
    { itemName = "grain_sack_b",      id = "grain_sack_b",     label = "item_grain_sack_b",     prop = "p_floursackstack02x",                  category = "storage",    price = { cash = 5,  gold = 0 }, weight = 1.0 },
    { itemName = "gourd",             id = "gourd",            label = "item_gourd",            prop = "p_gourdwater01x",                      category = "storage",    price = { cash = 5,  gold = 0 }, weight = 1.0 },
    { itemName = "basket_a",          id = "basket_a",         label = "item_basket_a",         prop = "p_basketindian01x",                    category = "storage",    price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "basket_b",          id = "basket_b",         label = "item_basket_b",         prop = "p_basketindian02x",                    category = "storage",    price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "pottery_a",         id = "pottery_a",        label = "item_pottery_a",        prop = "p_potteryindian05x",                   category = "storage",    price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "pottery_b",         id = "pottery_b",        label = "item_pottery_b",        prop = "p_potteryindian08x",                   category = "storage",    price = { cash = 9,  gold = 0 }, weight = 1.0 },
    { itemName = "pottery_c",         id = "pottery_c",        label = "item_pottery_c",        prop = "p_potteryindian07x",                   category = "storage",    price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "bowl",              id = "bowl",             label = "item_bowl",             prop = "p_bowlna01x",                          category = "storage",    price = { cash = 5,  gold = 0 }, weight = 1.0 },
    { itemName = "cloth_pile",        id = "cloth_pile",       label = "item_cloth_pile",       prop = "s_clothpile01x",                       category = "storage",    price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "hide_roll",         id = "hide_roll",        label = "item_hide_roll",        prop = "s_cvan_hideroll01",                    category = "storage",    price = { cash = 9,  gold = 0 }, weight = 1.0 },

    -- DECORATION -------------------------------------------------------------
    { itemName = "totem_a",           id = "totem_a",          label = "item_totem_a",          prop = "p_spookynative04x",                    category = "decoration", price = { cash = 10, gold = 0 }, weight = 1.0 },
    { itemName = "totem_b",           id = "totem_b",          label = "item_totem_b",          prop = "p_spookynative07x",                    category = "decoration", price = { cash = 11, gold = 0 }, weight = 1.0 },
    { itemName = "totem_staff",       id = "totem_staff",      label = "item_totem_staff",      prop = "p_staffindian03x",                     category = "decoration", price = { cash = 11, gold = 0 }, weight = 1.0 },
    { itemName = "totem_c",           id = "totem_c",          label = "item_totem_c",          prop = "p_spookynative05x",                    category = "decoration", price = { cash = 10, gold = 0 }, weight = 1.0 },
    { itemName = "totem_d",           id = "totem_d",          label = "item_totem_d",          prop = "p_spookynative12x",                    category = "decoration", price = { cash = 12, gold = 0 }, weight = 1.0 },
    { itemName = "skull_stones",      id = "skull_stones",     label = "item_skull_stones",     prop = "p_spookynative02x",                    category = "decoration", price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "skull_post",        id = "skull_post",       label = "item_skull_post",       prop = "p_skullpost02x",                       category = "decoration", price = { cash = 12, gold = 0 }, weight = 1.0 },
    { itemName = "skull_tip_a",       id = "skull_tip_a",      label = "item_skull_tip_a",      prop = "p_spookyskulls07bx",                   category = "decoration", price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "skull_tip_b",       id = "skull_tip_b",      label = "item_skull_tip_b",      prop = "p_spookyskulls07ax",                   category = "decoration", price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "skull_totem_small", id = "skull_totem_small",label = "item_skull_totem_small",prop = "p_spookyskulls04x",                    category = "decoration", price = { cash = 10, gold = 0 }, weight = 1.0 },
    { itemName = "stone_tomahawk",    id = "stone_tomahawk",   label = "item_stone_tomahawk",   prop = "p_indianartifact01x",                  category = "decoration", price = { cash = 12, gold = 0 }, weight = 1.0 },
    { itemName = "dreamcatcher",      id = "dreamcatcher",     label = "item_dreamcatcher",     prop = "p_indiandream01x_a",                   category = "decoration", price = { cash = 9,  gold = 0 }, weight = 1.0 },
    { itemName = "feather_tip",       id = "feather_tip",      label = "item_feather_tip",      prop = "p_spookynative01x",                    category = "decoration", price = { cash = 5,  gold = 0 }, weight = 1.0 },
    { itemName = "rattle_hanging",    id = "rattle_hanging",   label = "item_rattle_hanging",   prop = "p_spookynative09x",                    category = "decoration", price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "dreamcatcher_bead", id = "dreamcatcher_bead",label = "item_dreamcatcher_bead",prop = "p_indiandream01x",                     category = "decoration", price = { cash = 11, gold = 0 }, weight = 1.0 },
    { itemName = "feather_decor",     id = "feather_decor",    label = "item_feather_decor",    prop = "p_indianfan01x",                       category = "decoration", price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "skull_totem_large", id = "skull_totem_large",label = "item_skull_totem_large",prop = "p_group_skull01x",                     category = "decoration", price = { cash = 15, gold = 0 }, weight = 1.0 },
    { itemName = "skull_spear_trio",  id = "skull_spear_trio", label = "item_skull_spear_trio", prop = "p_spookyskulls02x_a",                  category = "decoration", price = { cash = 12, gold = 0 }, weight = 1.0 },
    { itemName = "bone_catcher",      id = "bone_catcher",     label = "item_bone_catcher",     prop = "p_hangingbones01x",                    category = "decoration", price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "totem_hanging",     id = "totem_hanging",    label = "item_totem_hanging",    prop = "p_target06x",                          category = "decoration", price = { cash = 10, gold = 0 }, weight = 1.0 },
    { itemName = "bearskin",          id = "bearskin",         label = "item_bearskin",         prop = "p_bearskin01x",                        category = "decoration", price = { cash = 16, gold = 0 }, weight = 1.0 },
    { itemName = "cattle_skull",      id = "cattle_skull",     label = "item_cattle_skull",     prop = "p_skullcattle03x",                     category = "decoration", price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "xmas_tree",         id = "xmas_tree",        label = "item_xmas_tree",        prop = "mp006_p_xmastree01x",                  category = "decoration", price = { cash = 12, gold = 0 }, weight = 1.0 },
    { itemName = "xmas_candy",        id = "xmas_candy",       label = "item_xmas_candy",       prop = "mp006_s_markercandycane",              category = "decoration", price = { cash = 5,  gold = 0 }, weight = 1.0 },
    { itemName = "xmas_ginger",       id = "xmas_ginger",      label = "item_xmas_ginger",      prop = "mp006_s_markergingerbread",            category = "decoration", price = { cash = 5,  gold = 0 }, weight = 1.0 },
    { itemName = "xmas_gift",         id = "xmas_gift",        label = "item_xmas_gift",        prop = "mp006_s_lootablechest03x",             category = "decoration", price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "xmas_wreath",       id = "xmas_wreath",      label = "item_xmas_wreath",      prop = "mp006_p_wreath01x",                    category = "decoration", price = { cash = 7,  gold = 0 }, weight = 1.0 },

    -- UTILITY ----------------------------------------------------------------
    { itemName = "hitchpost_wood",    id = "hitchpost_wood",   label = "item_hitchpost_wood",   prop = "p_hitchingpost01x",                    category = "utility",    price = { cash = 9,  gold = 0 }, weight = 1.0 },
    { itemName = "target_practice",   id = "target_practice",  label = "item_target_practice",  prop = "p_target01x",                          category = "utility",    price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "water_pump",        id = "water_pump",       label = "item_water_pump",       prop = "p_waterpump01x",                       category = "utility",    price = { cash = 20, gold = 0 }, weight = 1.0 },
    { itemName = "strawman",          id = "strawman",         label = "item_strawman",         prop = "s_confedtarget",                       category = "utility",    price = { cash = 6,  gold = 0 }, weight = 1.0 },
    { itemName = "fence_a",           id = "fence_a",          label = "item_fence_a",          prop = "p_fence06ax",                          category = "utility",    price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "fence_b",           id = "fence_b",          label = "item_fence_b",          prop = "p_fence10cx",                          category = "utility",    price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "fence_wall_a",      id = "fence_wall_a",     label = "item_fence_wall_a",     prop = "p_fence_wall01x",                      category = "utility",    price = { cash = 13, gold = 0 }, weight = 1.0 },
    { itemName = "fence_wall_b",      id = "fence_wall_b",     label = "item_fence_wall_b",     prop = "p_fence_wall02x",                      category = "utility",    price = { cash = 13, gold = 0 }, weight = 1.0 },
    { itemName = "barricade",         id = "barricade",        label = "item_barricade",        prop = "p_barricadewood_sml01x",               category = "utility",    price = { cash = 10, gold = 0 }, weight = 1.0 },
    { itemName = "bounty_board",      id = "bounty_board",     label = "item_bounty_board",     prop = "mp005_p_mp_bountyboard02x",            category = "utility",    price = { cash = 15, gold = 0 }, weight = 1.0 },
    -- { itemName = "gatling_gun",       id = "gatling_gun",      label = "item_gatling_gun",      prop = "gatlingMaxim02",                       category = "utility",    price = { cash = 20, gold = 0 }, weight = 1.0 },
    { itemName = "jump_hay",          id = "jump_hay",         label = "item_jump_hay",         prop = "mp001_p_mp_jump_haybaleshort01",       category = "utility",    price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "jump_fence",        id = "jump_fence",       label = "item_jump_fence",       prop = "mp001_p_mp_jump_fenceshort02",         category = "utility",    price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "jump_sack",         id = "jump_sack",        label = "item_jump_sack",        prop = "mp001_p_mp_jump_sackshort01",          category = "utility",    price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "jump_barrel",       id = "jump_barrel",      label = "item_jump_barrel",      prop = "mp001_p_mp_jump_barrelshort01",        category = "utility",    price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "jump_block",        id = "jump_block",       label = "item_jump_block",       prop = "mp001_p_mp_jump_blocksmall01",         category = "utility",    price = { cash = 8,  gold = 0 }, weight = 1.0 },
    { itemName = "jump_dock",         id = "jump_dock",        label = "item_jump_dock",        prop = "mp001_p_mp_jump_dock01",               category = "utility",    price = { cash = 9,  gold = 0 }, weight = 1.0 },
    { itemName = "jump_hurdle",       id = "jump_hurdle",      label = "item_jump_hurdle",      prop = "mp001_p_jumphurdles01x",               category = "utility",    price = { cash = 7,  gold = 0 }, weight = 1.0 },
    { itemName = "baby_stroller",     id = "baby_stroller",    label = "item_baby_stroller",    prop = "p_babystroller",                       category = "utility",    price = { cash = 12, gold = 0 }, weight = 1.0 },
    { itemName = "gold_cradle",       id = "gold_cradle",      label = "item_gold_cradle",      prop = "p_goldcradlestand01x",                 category = "utility",    price = { cash = 19, gold = 0 }, weight = 1.0 },
    { itemName = "drying_rack",       id = "drying_rack",      label = "item_drying_rack",      prop = "p_dryingmeat01x",                      category = "utility",    price = { cash = 10, gold = 0 }, weight = 1.0 },
    { itemName = "hide_frame",        id = "hide_frame",       label = "item_hide_frame",       prop = "mp005_p_mp_hideframe02x",              category = "utility",    price = { cash = 11, gold = 0 }, weight = 1.0 },
    { itemName = "hitchpost_metal",   id = "hitchpost_metal",  label = "item_hitchpost_metal",  prop = "p_horsehitchnbd01x",                   category = "utility",    price = { cash = 13, gold = 0 }, weight = 1.0 },
    { itemName = "counter_a",         id = "counter_a",        label = "item_counter_a",        prop = "p_cabinet13x",                         category = "utility",    price = { cash = 13, gold = 0 }, weight = 1.0 },
    { itemName = "counter_b",         id = "counter_b",        label = "item_counter_b",        prop = "p_pedestalstand01x",                   category = "utility",    price = { cash = 12, gold = 0 }, weight = 1.0 },
    { itemName = "vendor_cart",       id = "vendor_cart",      label = "item_vendor_cart",      prop = "p_cartvend02x",                        category = "utility",    price = { cash = 18, gold = 0 }, weight = 1.0 },

    -- MOVE CAMP --------------------------------------------------------------
    { itemName = "caravan_wagon", id = "caravan_wagon_move", label = "item_caravan_wagon_move", prop = "s_wagoncaravan01a",                    category = "movecamp",   price = { cash = 20, gold = 0 }, weight = 1.0 },
}

-- ─── ITEM SETTINGS ───────────────────────────────────────────────────────────
-- Keys MUST match the `itemName` field in Config.CampItems above.
-- createCamp = true  → using this item starts the camp creation flow (base prop)
-- stash = true       → prop has a persistent stash (storage chest etc.)
-- limit              → stash item slot count
-- installDuration    → ms it takes to install this prop (default = Config.Settings.DefaultInstallDuration)
-- grassRadius        → grass suppression radius around the prop (metres)
-- installItems       → items required to install this prop, e.g.:
--   installItems = {
--       { itemName = "wood",   count = 1, dontRemove = false },  -- consumed on install
--       { itemName = "hammer", count = 1, dontRemove = true  },  -- kept (tool)
--   }

Config.CampItemSettings = {

    -- SHELTER — all tents create a camp ----------------------------------------
    ["tent_open"]         = { grassRadius = 5.0, createCamp = true,  installDuration = 8000 },
    ["tent_hunter"]       = { grassRadius = 5.0, createCamp = true,  installDuration = 8000 },
    ["tent_mountain"]     = { grassRadius = 5.0, createCamp = true,  installDuration = 8000 },
    ["tent_rain"]         = { grassRadius = 5.0, createCamp = true,  installDuration = 5000 },
    ["tent_tanner"]       = { grassRadius = 5.0, createCamp = true,  installDuration = 7000 },
    ["tent_lemoyne"]      = { grassRadius = 5.0, createCamp = true,  installDuration = 7000 },
    ["tent_hide_small"]   = { grassRadius = 5.0, createCamp = true,  installDuration = 6000 },
    ["tent_bison"]        = { grassRadius = 5.0, createCamp = true,  installDuration = 8000 },
    ["tent_swamp"]        = { grassRadius = 5.0, createCamp = true,  installDuration = 6000 },
    ["tent_mulch"]        = { grassRadius = 5.0, createCamp = true,  installDuration = 5000 },
    ["shelter_leanto"]    = { grassRadius = 5.0, createCamp = true,  installDuration = 4000 },
    ["shelter_debris"]    = { grassRadius = 5.0, createCamp = true,  installDuration = 4000 },
    ["caravan_wagon"]     = { grassRadius = 5.0, createCamp = true,  installDuration = 10000 },

    -- FURNITURE ----------------------------------------------------------------
    ["table_wood"]        = { grassRadius = 5.0,  installDuration = 3000 },
    ["chair_wood"]        = { grassRadius = 5.0,  installDuration = 2000 },
    ["bench_wood"]        = { grassRadius = 5.0,  installDuration = 2500 },
    ["cot"]               = { grassRadius = 5.0,  installDuration = 3000 },
    ["table_bespoke"]     = { grassRadius = 5.0,  installDuration = 3500 },
    ["stool_folding"]     = { grassRadius = 5.0, installDuration = 1500 },
    ["chair_folding"]     = { grassRadius = 5.0, installDuration = 1500 },
    ["chair_rustic"]      = { grassRadius = 5.0, installDuration = 2000 },
    ["bed_native_small"]  = { grassRadius = 5.0,  installDuration = 3000 },
    ["bed_native_large"]  = { grassRadius = 5.0,  installDuration = 3500 },
    ["bedroll"]           = { grassRadius = 5.0,  installDuration = 2000 },
    ["backrest"]          = { grassRadius = 5.0,  installDuration = 2000 },
    ["log_bench_large"]   = { grassRadius = 5.0,  installDuration = 3000 },
    ["log_bench_small"]   = { grassRadius = 5.0,  installDuration = 2500 },
    ["log_bench_medium"]  = { grassRadius = 5.0,  installDuration = 2500 },

    -- FIRE & COOKING -----------------------------------------------------------
    ["bonfire"]           = { grassRadius = 5.0,  installDuration = 3000 },
    ["firepit"]           = { grassRadius = 5.0,  installDuration = 3500 },
    ["kettle_fire"]       = { grassRadius = 5.0,  installDuration = 3000 },
    ["bread_oven"]        = { grassRadius = 5.0,  installDuration = 6000 },
    ["forge"]             = { grassRadius = 5.0,  installDuration = 8000 },
    ["anvil"]             = { grassRadius = 5.0,  installDuration = 5000 },
    ["anvil_stump"]       = { grassRadius = 5.0,  installDuration = 3000 },
    ["sawhorse"]          = { grassRadius = 5.0,  installDuration = 3500 },
    ["workbench"]         = { grassRadius = 5.0,  installDuration = 5000 },
    ["grindstone"]        = { grassRadius = 5.0,  installDuration = 5000 },
    ["coal_bin"]          = { grassRadius = 5.0,  installDuration = 3000 },

    -- LIGHTING -----------------------------------------------------------------
    ["lantern_oil"]       = { grassRadius = 5.0,  installDuration = 2000 },
    ["lamp_street"]       = { grassRadius = 5.0,  installDuration = 4000 },
    ["light_post"]        = { grassRadius = 5.0,  installDuration = 4000 },

    -- STORAGE — stash items (createCamp = true → these can start a camp) ---------
    ["chest_small"]       = { grassRadius = 5.0, createCamp = true, stash = true, limit = 100, installDuration = 5000 },
    ["chest_large"]       = { grassRadius = 5.0, createCamp = true, stash = true, limit = 200, installDuration = 7000 },
    ["trunk"]             = { grassRadius = 5.0, createCamp = true, stash = true, limit = 50,  installDuration = 4000 },
    ["barrel"]            = { grassRadius = 5.0, createCamp = true, stash = true, limit = 30,  installDuration = 3000 },
    ["crate"]             = { grassRadius = 5.0, createCamp = true, stash = true, limit = 20,  installDuration = 2500 },
    ["coffin"]            = { grassRadius = 0.1, createCamp = true, stash = true, limit = 50,  installDuration = 4000 },
    ["washbasin"]         = { grassRadius = 5.0,  installDuration = 2000 },
    ["dirt_tub"]          = { grassRadius = 5.0,  installDuration = 2000 },
    ["rope_basket"]       = { grassRadius = 5.0, createCamp = true, stash = true, limit = 20,  installDuration = 2000 },
    ["water_bucket"]      = { grassRadius = 5.0,  installDuration = 1500 },
    ["grain_sack_a"]      = { grassRadius = 5.0,  installDuration = 2000 },
    ["grain_sack_b"]      = { grassRadius = 5.0,  installDuration = 2000 },
    ["gourd"]             = { grassRadius = 5.0,  installDuration = 1500 },
    ["basket_a"]          = { grassRadius = 5.0, createCamp = true, stash = true, limit = 15,  installDuration = 2000 },
    ["basket_b"]          = { grassRadius = 5.0, createCamp = true, stash = true, limit = 15,  installDuration = 2000 },
    ["pottery_a"]         = { grassRadius = 5.0,  installDuration = 2000 },
    ["pottery_b"]         = { grassRadius = 5.0,  installDuration = 2000 },
    ["pottery_c"]         = { grassRadius = 5.0,  installDuration = 2000 },
    ["bowl"]              = { grassRadius = 5.0,  installDuration = 1500 },
    ["cloth_pile"]        = { grassRadius = 5.0,  installDuration = 2000 },
    ["hide_roll"]         = { grassRadius = 5.0,  installDuration = 2000 },

    -- DECORATION ---------------------------------------------------------------
    ["totem_a"]           = { grassRadius = 5.0,  installDuration = 3000 },
    ["totem_b"]           = { grassRadius = 5.0,  installDuration = 3000 },
    ["totem_staff"]       = { grassRadius = 5.0,  installDuration = 2500 },
    ["totem_c"]           = { grassRadius = 5.0,  installDuration = 3000 },
    ["totem_d"]           = { grassRadius = 5.0,  installDuration = 3000 },
    ["skull_stones"]      = { grassRadius = 5.0,  installDuration = 3000 },
    ["skull_post"]        = { grassRadius = 5.0,  installDuration = 3500 },
    ["skull_tip_a"]       = { grassRadius = 5.0,  installDuration = 2000 },
    ["skull_tip_b"]       = { grassRadius = 5.0,  installDuration = 2000 },
    ["skull_totem_small"] = { grassRadius = 5.0,  installDuration = 3000 },
    ["stone_tomahawk"]    = { grassRadius = 5.0,  installDuration = 2000 },
    ["dreamcatcher"]      = { grassRadius = 5.0,  installDuration = 2500 },
    ["feather_tip"]       = { grassRadius = 5.0,  installDuration = 2000 },
    ["rattle_hanging"]    = { grassRadius = 5.0,  installDuration = 2000 },
    ["dreamcatcher_bead"] = { grassRadius = 5.0,  installDuration = 2500 },
    ["feather_decor"]     = { grassRadius = 5.0,  installDuration = 2000 },
    ["skull_totem_large"] = { grassRadius = 5.0,  installDuration = 3500 },
    ["skull_spear_trio"]  = { grassRadius = 5.0,  installDuration = 3000 },
    ["bone_catcher"]      = { grassRadius = 5.0,  installDuration = 2500 },
    ["totem_hanging"]     = { grassRadius = 5.0,  installDuration = 2500 },
    ["bearskin"]          = { grassRadius = 5.0,  installDuration = 3000 },
    ["cattle_skull"]      = { grassRadius = 5.0,  installDuration = 2500 },
    ["xmas_tree"]         = { grassRadius = 5.0,  installDuration = 4000 },
    ["xmas_candy"]        = { grassRadius = 5.0,  installDuration = 1500 },
    ["xmas_ginger"]       = { grassRadius = 5.0,  installDuration = 1500 },
    ["xmas_gift"]         = { grassRadius = 5.0,  installDuration = 2000 },
    ["xmas_wreath"]       = { grassRadius = 5.0,  installDuration = 2000 },

    -- UTILITY ------------------------------------------------------------------
    ["hitchpost_wood"]    = { grassRadius = 5.0, installDuration = 3000 },
    ["target_practice"]   = { grassRadius = 5.0, installDuration = 2000 },
    ["water_pump"]        = { grassRadius = 5.0,  installDuration = 8000 },
    ["strawman"]          = { grassRadius = 5.0,  installDuration = 2500 },
    ["fence_a"]           = { grassRadius = 5.0,  installDuration = 3000 },
    ["fence_b"]           = { grassRadius = 5.0,  installDuration = 3000 },
    ["fence_wall_a"]      = { grassRadius = 5.0,  installDuration = 4000 },
    ["fence_wall_b"]      = { grassRadius = 5.0,  installDuration = 4000 },
    ["barricade"]         = { grassRadius = 5.0,  installDuration = 3000 },
    ["bounty_board"]      = { grassRadius = 5.0,  installDuration = 4000 },
    ["gatling_gun"]       = { grassRadius = 2.0,  installDuration = 10000 },
    ["jump_hay"]          = { grassRadius = 5.0,  installDuration = 2500 },
    ["jump_fence"]        = { grassRadius = 5.0,  installDuration = 2500 },
    ["jump_sack"]         = { grassRadius = 5.0,  installDuration = 2500 },
    ["jump_barrel"]       = { grassRadius = 5.0,  installDuration = 2500 },
    ["jump_block"]        = { grassRadius = 5.0,  installDuration = 2500 },
    ["jump_dock"]         = { grassRadius = 5.0,  installDuration = 3000 },
    ["jump_hurdle"]       = { grassRadius = 5.0,  installDuration = 2500 },
    ["baby_stroller"]     = { grassRadius = 5.0,  installDuration = 2500 },
    ["gold_cradle"]       = { grassRadius = 2.0,  installDuration = 6000 },
    ["drying_rack"]       = { grassRadius = 5.0,  installDuration = 4000 },
    ["hide_frame"]        = { grassRadius = 5.0,  installDuration = 4000 },
    ["hitchpost_metal"]   = { grassRadius = 5.0,  installDuration = 3500 },
    ["counter_a"]         = { grassRadius = 5.0,  installDuration = 4000 },
    ["counter_b"]         = { grassRadius = 5.0,  installDuration = 3500 },
    ["vendor_cart"]       = { grassRadius = 5.0,  installDuration = 5000 },
}
